### ISSUE TITLE
env.RunScript  require is not defined

### ISSUE THREAD

**Issue by colorhacker** [nodejs/node-addon-api#1012]
Why can the console be executed, but the requirements are not defined?

```
`
const fs = require("fs"); 
console.log(1);
`
```
```
Napi::Value test(const Napi::CallbackInfo& info){
    Napi::Env env = info.Env();
    std::string text = info[0].As<Napi::String>().Utf8Value();
	env.RunScript(Napi::String::New(env,(const char*)text.data(),(size_t )text.length()));
	return info.Env().Undefined();
}
```

**Comment by mhdawson** [comment]
@colorhacker I don't quite understand the question from what you have in the issue.

**Comment by KevinEady** [comment]
@colorhacker , if I understand your question correctly, you want to call `env.RunScript()` on a string that calls `require()` inside of it. The problem is that `require` is a pseudo-global and is only available in the caller .js script, see [The built-in globals in Node.js](https://nodejs.org/en/knowledge/getting-started/globals-in-node-js/). You get the same error if you try to use the `vm` module, eg. `require('vm').runInNewContext("require")`:

```
ReferenceError: require is not defined
```

You need to pass the `require` function into your addon somehow. If you are intending to use `RunScript`, your string javascript code needs to return a function that accepts the `require` parameter, and then you can call `returnVal(require)` in the calling .js
