### ISSUE TITLE
libuv and WorkerThreads

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#1060]
My add-on has been implemented before WorkerThreads were available and is still using libuv.

Would it make sense to replace the libuv with WorkerThreads and what would be key advantages/disadvantages? Feedback on experience with the migration would be welcome as well.

Question is related to recent feature request: https://github.com/SAP/node-rfc/issues/232#issuecomment-909038795

**Comment by mhdawson** [comment]
From discussion in the Node-API team meeting today:

* Potential Advantages
  * Removing dependency on libuv which is not guaranteed ABI stable. However, you can likely get the same 
     benefit by creating threads without using libuv and possibly use ThreadSafeFunction.
* Potential Disadvantage
  * Possibly more overhead getting data back to main thread at JS level (communication between worker threads)
  * More overhead because there would be a JavaScript execution environment (heap, etc.) for each
    WorkerThread. Unless you need concurrent JavaScript execution this is just a cost versus a benefit
  * Will likely still need to manage pool of Worker threads, more work to do that, but more control

The Node-api did not have any specific experience to relate on migrating from using libuv thread to using Workers instead.

**Comment by bsrdjan** [comment]
Thank you @mhdawson, my add-on will stay with libuv for the time being.

In addition to libuv I am actually using also WorkerThreads. Wrapped external library requires one API method to be called from a different thread and I recently added WorkerThreads for that purpose. All works fine and I did not notice below two points because API requires only one long int to be transferred back and forth. Scaling to complex business data structures and volumes would make these points very "visible" in my case:

> - Possibly more overhead getting data back to main thread at JS level (communication between worker threads)
> - More overhead because there would be a JavaScript execution environment (heap, etc.) for each
WorkerThread.

Having no further questions I am closing the issue.
