### ISSUE TITLE
Exception in ObjectWrap Constructor are not thrown as Napi::Error

### ISSUE THREAD

**Issue by kelvinhammond** [nodejs/node-addon-api#1104]
I have a class that throws an exception in its constructor, the exception is not caught and rethrown as a `Napi::Error` exception, is this expected or is there a setting I should be turning on. From the docs it seems like this should be working.

```
#ifdef NAPI_CPP_EXCEPTIONS
  throw std::runtime_error("Hello runtime");
#endif
```

Output
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Hello runtime
```

**Comment by JckXia** [comment]
Hey there. If you don't mind, can you post some code snippets that can reproduce this error? Is your expected behavior to be able to catch this exception from js/ or from another C++ function that is calling this constructor?

**Comment by gabrielschulhof** [comment]
@kelvinhammond our convert-to-JS-exception code catches only `Napi::Error` objects:

https://github.com/nodejs/node-addon-api/blob/706b19986da2f247da69bfb932753c1eb2ede894/napi-inl.h#L69-L85

**Comment by kelvinhammond** [comment]
@gabrielschulhof Is there a way for it to automatically catch `std:exception` objects too? Is there a way to wrap my object `constructors` via the `ObjectWrap` api?

**Comment by gabrielschulhof** [comment]
@kelvinhammond in order to catch a `std::exception` we would have to have a systematic way of turning it into a `Napi::Error` object. We could do this with the `what()` method, but that might be insufficient and/or undesirable for some applications because such a conversion seems application-specific. It would be better if you wrapped your call to the C++ API that may throw a `std::exception` into a try-catch block, then processed and re-threw the `std::exception` as a `Napi::Error` in its `catch` block.

**Comment by mhdawson** [comment]
We discussed in the Node-API team meeting today. There was a suggestion made and no follow up/questions since then closing. Please let us know if that was not the right thing to do.
