### ISSUE TITLE
Is documentation outdated?

### ISSUE THREAD

**Issue by developer239** [nodejs/node-addon-api#1106]
Is the documentation outdated?

https://github.com/nodejs/node-addon-api/blob/main/doc/class_property_descriptor.md#class-property-and-descriptor

Instead of `InstanceAccessor<&Example::GetValue>("readOnlyProp")`

it should be: `InstanceAccessor("getValue", &Point::getValue, nullptr)`

What am I missing? 🙂

**Comment by developer239** [comment]
This one and pretty much everything as well?

https://github.com/nodejs/node-addon-api/blob/main/doc/object_wrap.md

**Comment by mhdawson** [comment]
We discussed in the Node-API team meeting today. @gabrielschulhof mentioned that they are both legal due to the overrides that are in place. 

The are documented in the common base class in https://github.com/nodejs/node-addon-api/blob/main/doc/instance_wrap.md

What makes sense to open the section by saying that this is a helper class created with the InstanceWrap methods and point to the InstanceWrap and ObjectWrap sections.

@gabrielschulhof will submit a PR to update the docs.

**Comment by mhdawson** [comment]
@NickNaso is going to take a look this week.

**Comment by mhdawson** [comment]
Since there is a PR for this  taking off the stale review list.

**Comment by mhdawson** [comment]
The PR to address the issue was merged so closing.
