### ISSUE TITLE
Very high memory usage with AsyncProgressQueueWorker on Linux

### ISSUE THREAD

**Issue by SkyBladeCloud** [nodejs/node-addon-api#1167]
Hello all,

I'm running into a very strange issue porting a tool to use AsyncProgressQueueWorker:

My application reads and processes large sensor data files. Thus, the worker thread loop (in Execute) reads a data block from the file, allocating the required memory for it. Then in the main thread (in OnProgress) I wrap the data on an ArrayBuffer and pass it as parameter to the JS callback (where the rest of the processing is done).
I do free the previously allocated data in the finalizer of the ArrayBuffer.

While this seems to perfectly work, in Linux I observe the memory usage of the process grows to almost the full length of the input file (about 9 out of 10 GB) at the beginning and is never released.
What's really strange is that exactly the same code perfectly works on Windows, where the memory usage grows at the beginning, then gradually decreases, and usage is about the same before and after the whole worker run.

I'm not familiar with NAPI's codebase, but I assume the produced data on the worker thread is being queued somewhere while the main thread dispatches it. Could it be that this queue never shrinks in Linux? The memory usage seems to always be the maximum queue size, which would in turn depends on how fast the worker thread can accumulate the data, vs how fast the main thread can consume it.
I tried purposely delaying the worker thread (just sleeping on it for a few microseconds per loop iteration) and sure enough, memory usage never grows too much like this (suggesting the main thread has more time to consume the data and the queue never needs to grow that much).

More Information:

- Tried on Windows Node v15.5.1 -> Working as expected
- Tried on Ubuntu 24.04 Node v15.5.1 -> High memory usage
- Tried on Ubuntu 24.04 Node v16.14.2 -> High memory usage
- Tried both latest master as well as NAPI 4.3.0
- I can confirm the "onProgress" method runs the right amount of times (once every time "Send" is called from the worker thread).
- I can confirm the finalizer of the ArrayBuffers is running as expected.

I can reproduce the behavior described in this issue using the EchoWorker example from:

https://github.com/nodejs/node-addon-api/blob/main/doc/async_worker_variants.md

Instead of just looping 100 times as done in the example, doing it many more times (I tried 1B times) would eventually create a noticeable delay between worker and main threads and the expanded queue will keep its size after the execution ends.

Is there any way I can further profile the memory usage of an AsyncProgressQueueWorker?

Thank you very much and kind regards,

~Sky

**Comment by mhdawson** [comment]
This is the code were data will be pushed - https://github.com/nodejs/node/blob/718be08686312d19645861b9715491a49ee3c9cb/src/node_api.cc#L149

We use a std::queue as defined here:
https://github.com/nodejs/node/blob/718be08686312d19645861b9715491a49ee3c9cb/src/node_api.cc#L423

It looks like we don't specific the container so it would default to std:deque based on https://en.cppreference.com/w/cpp/container/queue

From https://en.cppreference.com/w/cpp/container/deque it says:

> The storage of a deque is automatically expanded and contracted as needed. Expansion of a deque is cheaper than the expansion of a [std::vector](https://en.cppreference.com/w/cpp/container/vector) because it does not involve copying of the existing elements to a new memory location. On the other hand, deques typically have large minimal memory cost; a deque holding just one element has to allocate its full internal array (e.g. 8 times the object size on 64-bit libstdc++; 16 times the object size or 4096 bytes, whichever is larger, on 64-bit libc++).

deque does have  shrink_to_fit method -> https://en.cppreference.com/w/cpp/container/deque/shrink_to_fit

@SkyBladeCloud you could experiment with trying to call shrink_to_fit after the pops (for example - https://github.com/nodejs/node/blob/718be08686312d19645861b9715491a49ee3c9cb/src/node_api.cc#L297) to see what difference that makes.

The other aspect is wether the lager memory you see is actuallly holding memory in a way that it won't be freed or can't already be re-used. For example if what you are looking at is `vitual memory size` then that might not matter in terms of real memory.  Simarly since deque is supposed to manage shriking there may just not have been enough memory pressure to make it shrink and if there is pressure it would give up the memory it's using. The true memory usage in terms of real impact to other parts of the code needing memory or other processes needed memory can often be difficult to determine.

**Comment by SkyBladeCloud** [comment]
Thank you very much @mhdawson for your insight.

I had the chance to compile Node myself and try some of your suggestions but I'm afraid I'm still at a loss:

- Due to the fact that the queue is defined as std::queue. I don't have access to the underlying container to call shrink_to_fit(), but changing it to a std::deque and calling it, didn't help.
- I tried running several sequential AsyncProgressQueueWorker's in order to fill up the system memory (see if node would eventually give it up). Unfortunately it did fill up and started giving "Out of memory" errors in dmesg (killing the node process).

For now I'll try to work around this issue by implementing my own producer-consumer on top of napi's tsfn. Once I get some more time I'll revisit this issue to try to get to the bottom of it.

Thanks again and kind regards!

~Sky

**Comment by mhdawson** [comment]
@SkyBladeCloud thanks for the update and let us know if you learn more.

**Comment by mhdawson** [comment]
Closing as there has not been a response for over 3 months. Please let us know if that was not the right thing to do.
