### ISSUE TITLE
How to call  addon multi time

### ISSUE THREAD

**Issue by Deuscx** [nodejs/node-addon-api#1204]
when call addon multi time it throw error
[node-addon-api/threadsafe_function.md](https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe_function.md)

```js
const { start } = require('bindings')('addon');

start(function () {
    console.log("JavaScript callback called with arguments", Array.from(arguments));
}, 5);

// call second time  throw an error
start(function () {
    console.log("JavaScript callback called with arguments", Array.from(arguments));
}, 5);
```
- example: https://github.com/Deuscx/addon-call-multi

**Comment by KevinEady** [comment]
Hi @Deuscx , 

This tsfn example is a pretty simple example that just highlights how to use the APIs. It is _not_ context-aware (meaning it can only be loaded one time) and also _cannot_ be called multiple times. The lines [here](https://github.com/Deuscx/addon-call-multi/blob/6a8097497894c22964a1de0027011be58cfa0241/addon.cc#L7-L8) declare variables that are used throughout the instance and are written to when the `Start()` method is called. The addon will crash if multiple `Start()` methods are called because the `tsfn` and `nativeThread` values are overwritten. You would need to rearchitect the example to suit your specific needs if you want to call this `Start()` method multiple times, eg. using an `ObjectWrap`'d instance to store the `std::thread` and `ThreadSafeFunction`, and passing the TSFN instance to the native thread.

Hope this clarifies your question. Let us know if you need further assistance.

**Comment by Deuscx** [comment]
@KevinEady  Thanks. it save my time
