### ISSUE TITLE
[QUESTION] How does the finalizer actually work?

### ISSUE THREAD

**Issue by ammarfaizi2** [nodejs/node-addon-api#1212]
How does the finalizer actually work?

I have created many objects with:
```
Napi::Object obj = Napi::Object::New(env);
obj.AddFinalizer(MyDeleter, my_ptr);
```

But the finalizer is only called when my program exits. I want to make
the NodeJS call `MyDeleter()` when the object lifetime ends.

**Comment by ammarfaizi2** [comment]
This is very problematic especially when we have a large C++ object
that needs to be destroyed soon once the NodeJS object ends.

I create a simple reproducer that simulates my issue.

## C++ code
```cpp
#include <cstdio>
#include <cstdlib>
#include "../node-addon-api/napi.h"

static void MyDeleter(Napi::Env env, int *my_ptr)
{
	printf("MyDeleter is called!\n");
	delete[] my_ptr;
}

static Napi::Value Create(const Napi::CallbackInfo &info)
{
	Napi::Env env = info.Env();
	Napi::Object obj = Napi::Object::New(env);

	obj["test"] = Napi::String::New(env, "test_string");
	obj.AddFinalizer(MyDeleter, new int[1000]);
	return obj;
}

static Napi::Object Init(Napi::Env env, Napi::Object exports)
{
	exports["create"] = Napi::Function::New(env, Create);
	return exports;
}
NODE_API_MODULE(chnet, Init);
```

## NodeJS code
```js
while (1) {
	let obj = chnet.create();

	if (obj.test != "test_string") {
		console.log("invalid!");
	}
}
```

The `MyDeleter` function is never called here because the program
never exits by its own. This results in memory leak due to deferred
finalizer calls. You can see high amount of memory usage pretty soon
from the `new int[1000]`.

Please fix the finalizer API. The finalizer is useless if it's only
called when the program exits, because the OS will automatically
reclaim that memory when the program exits anyway, even if I don't
call `delete[] my_ptr`.

**Comment by ammarfaizi2** [comment]
OK, it seems I misunderstand how GC works here.

I took a look at https://github.com/nodejs/node-addon-api/issues/917.
But I still don't understand the proper workaround for this. Please
shed some light.

**Comment by KevinEady** [comment]
Hi @ammarfaizi2 , 

The finalizer gets ran when the GC decides it needs to run due to running on limited memory. The only way to forcibly run the GC is to start node with `--expose-gc` flag, which then provides a `gc()` function on the `global` object. We have a test ([js](https://github.com/nodejs/node-addon-api/blob/793268c59f8c14a56f44ef00a7711c18d1c35b95/test/buffer.js#L41-L53), [cpp](https://github.com/nodejs/node-addon-api/blob/793268c59f8c14a56f44ef00a7711c18d1c35b95/test/array_buffer.cc#L87-L117)) that (1) creates an `ArrayBuffer`, whose finalizer increases an internal counter, (2) runs the garbage collector, and (3) asserts the finalizer was ran by checking the internal counter.

Does this answer your questions? Let us know if you need additional assistance.

Thanks, Kevin

**Comment by KevinEady** [comment]
Hi @ammarfaizi2 ,

@vmoroz clarified in today's Node API meeting that the finalizers do not actually run when the GC runs, but is _scheduled to run_ via `SetImmediate` by the GC run.

**Comment by ammarfaizi2** [comment]
> Does this answer your questions? Let us know if you need additional assistance.

Hi,

Thanks for the response. What is `SetImmediate`?

**Comment by KevinEady** [comment]
Hi @ammarfaizi2 ,

`SetImmediate` is used to schedule tasks to be completed after IO callbacks. You can find more information here: [setImmediate](https://nodejs.org/api/timers.html#setimmediatecallback-args)
