### ISSUE TITLE
The corresponding napi_create_int64 interface was not found in the node-addon-api，is it not supported?

### ISSUE THREAD

**Issue by Candylong** [nodejs/node-addon-api#1231]

**Comment by NickNaso** [comment]
Hi @Candylong,
you can simply do this:
```cpp
// ...
int64_t number = 10;
Napi::Number jsNumber = Napi::Number::New(env, number);
```
the problem is that you cannot represent all the complete range for `inte64_t` see: https://tc39.es/ecma262/#sec-ecmascript-language-types-number-type ([Number.MIN_SAFE_INTEGER](https://tc39.es/ecma262/#sec-number.min_safe_integer) - [Number.MAX_SAFE_INTEGER](https://tc39.es/ecma262/#sec-number.max_safe_integer)).
If you want to represent an integer type without the previous limitation the `Napi::BigInt` is more convenient (https://github.com/nodejs/node-addon-api/blob/main/doc/bigint.md). 
Let me know if this help you.

**Comment by Candylong** [comment]
@NickNaso , 
Thanks for your reply, if I want to represent a c function address, then should I use Napi::BigInt or Napi::Number
