### ISSUE TITLE
How to return values from addon to JavaScript via function arguments

### ISSUE THREAD

**Issue by wanglin86769** [nodejs/node-addon-api#1285]
Hello, after going through node-addon-examples, I still do not know how to return values via function arguments. For example, I have two use cases.

Case 1:
I want to invoke functions from a shared library in addon. Some functions from the shared library are like this,
`STATUS add(int x, int y, int *result);`

How can I use the add() function in addon and return the value via the function argument in JavaScript?
```
var addon = require('bindings')('test');
let result = {};
addon.add(10, 20, result);
console.log(result);
```

Case 2:
The value need to be returned via the function argument, but I do not care its structure and specific value since it is only used by the shared library itself. The related functions in the shared library are like this,
```
STATUS create_channel(char * name, int priority, CHANNEL_ID * ptr_channel_id);
STATUS get_value(CHANNEL_ID channel_id, int *value); 
```

How can I implement this in JavaScript like this?
```
var addon = require('bindings')('test');
let channel_id = {};
let value = {};
create_channel('Test Name', 0, channel_id );
get_value(channel_id, value);
console.log(value); 
```

Any suggestion is appreciated, thanks.

**Comment by KevinEady** [comment]
Hi @wanglin86769 ,

Since JavaScript objects are passed by reference, you can modify the properties of the object coming into your native function.

```js
var addon = require('bindings')('test');
let result = {};
addon.add(10, 20, result);
console.log(result);
```

Your native function would be able to modify the `result` object's properties, eg. adding a new property `result`:

```cpp
Value Add(const CallbackInfo& cb) {
    auto env =  cb.Env();

    int result;
    add(x, y, &result);

    cb[2].As<Object>().Set("result", Number::New(env, result));

    return env.Undefined();
}
```
After calling this method, `result.result` will contain the integer value of the output parameter of `add`.

For case 2, you can use `Napi::External<CHANNEL_ID>` to hold an externally allocated value.

```js
var addon = require('bindings')('test');
let channel_id = {};
let value = {};
create_channel('Test Name', 0, channel_id );
get_value(channel_id, value);
console.log(value); 
```

```cpp
Value CreateChannel(const CallbackInfo& cb) {
    auto env = cb.Env();

    CHANNEL_ID* channel_id = new CHANNEL_ID;
    create_channel(name, priority, &channel_id);

    cb[2].As<Object>().Set("channelId", External::New(env, channel_id, [](Napi::Env, CHANNEL_ID* data) { delete data; }));

    return env.Undefined();
}
```

After calling this method, `result.channelId` will contain the integer value of the output parameter of `create_channel`.

You can then use this `External` as a normal javascript value:

```cpp
Value GetValue(const CallbackInfo& cb) {
    auto env =  cb.Env();
    auto channel_id = cb[0].As<External<CHANNEL_ID>>();

    int value;
    get_value(*(channel_id.Data()), value);

    cb[1].As<Object>().Set("result", Number::New(env, value));

    return env.Undefined();
}
```

Does this clarify your questions?

**Comment by wanglin86769** [comment]
@KevinEady Thank you very much for the reply, which perfectly answered my questions and helped me understand  the node-addon-api module much better.
