### ISSUE TITLE
How to invoke the JavaScript callback within shared library rather than addon

### ISSUE THREAD

**Issue by wanglin86769** [nodejs/node-addon-api#1287]
Hello, I am using node-addon-api to wrap a shared library so that JavaScript code can use the functions from the shared library. The problem is that some functions in the shared library have callback arguments, but I did not succeed to pass the JavaScript callback to the shared library via addon.
For example, my code snippet as follows does not work, and the callback that passed to get_value() within the shared library does not execute at all.

```
Napi::Value Callback_Test(const Napi::CallbackInfo& info) {
  if (!hGetProcIDDLL) {
    std::cout << "could not load the dynamic library" << std::endl;
    exit(EXIT_FAILURE);
  }

  CREATE_CHANNEL create_channel = (CREATE_CHANNEL)GetProcAddress(hGetProcIDDLL, "createChannel");
  if (!create_channel) {
    std::cout << "could not locate the function" << std::endl;
    exit(EXIT_FAILURE);
  }

  Napi::Env env = info.Env();

  Napi::Function cb = info[0].As<Napi::Function>();

  void * ptr_chan = NULL;
  create_channel(&ptr_chan);
  get_value(ptr_chan, 100, cb);
    
  return Napi::Number::New(env, 0);
}
```

```
var addon = require('bindings')('hello');

addon.load("C:\\Users\\wanglin\\source\\repos\\Dll3\\x64\\Debug\\Dll1.dll");

let myCallback = function myFunction(args) {
    console.log('*** Entering callback! ***');
    console.log(args);
}

addon.callback_test(myCallback);
```

**Comment by TheBoneJarmer** [comment]
Hey

I noticed there are no replies here yet so allow me to help you out, if you still need help that is. I once hit the same issue and had to do some extensive research on SO and here to figure it out. And probably my method isn't the best either but it works for me. First of all, converting a JS to C++ callback is not possible. So instead, you gotta call the JS function in a c++ callback using a `Napi::FunctionReference` object.

Since a JS callback is an object constructed and most-likely destructed soon after, you need make it persistent. So we start by declaring a `Napi::FunctionReference` object that holds a reference to the function instead of the function itself. See it as a `std::unique_ptr<T>` equivalent. The function reference keeps track of references to an object as well as the object. If there are no references left the object becomes available for the GC to be collected.

Secondly you have to create some sort of _setter_ method or whatever you'd call it, where you assign the reference object to a value, in this case the JS function. Also, notice the `SuppressDestruct` here. This is to prevent the GC from collecting it apparently. Don't know the details. And finally, you call the function reference from your c++ callback.

```c++
Napi::FunctionReference fun_ref;

void set_fun(const Napi::CallbackInfo &info) {
    Napi::Function fun = info[0].As<Napi::Function>();

    fun_ref = Napi::Persistent(fun);
    fun_ref.SuppressDestruct();
}

void callback(int int1, bool bool1) {
    Napi::Env env = fun_ref.Env();

    fun_ref.Call({}); // For calling the callback without arguments

    std::vector<napi_value> args; // Dunno why this has to be napi_value
    args.push_back(Napi::Number::New(env, int1));
    args.push_back(Napi::Boolean::New(env, bool1));

    fun_ref.Call(args);
}
```

I hope this more or less helps you out. I am no expert on the subject and for that reason I usually don't reply on issues here but seeing nobody did and because the whole support for callbacks is poorly documented I figured it probably couldn't hurt. Good luck!

**Comment by wanglin86769** [comment]
@TheBoneJarmer Hello, thank you so much for your reply. Recently I used a third-party FFI npm library called koffi to access the functions in the shared library. And I will try your method later.
