### ISSUE TITLE
Failing test on v16 and x86 platform

### ISSUE THREAD

**Issue by legendecas** [nodejs/node-addon-api#1290]
I think that I found the test that does not work:
https://github.com/nodejs/node-addon-api/blob/main/test/async_progress_worker.cc#L185
https://github.com/nodejs/node-addon-api/blob/main/test/async_progress_worker.js#L12

Anyone have an idea because this test hangs on Node.js v16 and x86 platform?

_Originally posted by @NickNaso in https://github.com/nodejs/node-addon-api/issues/1278#issuecomment-1415477148_

**Comment by JckXia** [comment]
I did some digging into this issue.  So far, it appears that a normal CI run will reliably reproduce this error. Occasionally, they will [succeed](https://github.com/nodejs/node-addon-api/pull/1295/checks) but that seems to be more of an exception than the norm. 

However, when I tried to run just this particular test using `node16` on X86 (https://github.com/JckXia/node-addon-api/actions/runs/4440582410/jobs/7794559762), it will pass with flying colors each time. I thought `async_progress_queue_worker` was the confounding factor but that doesn't seem to make much of a difference.

Does anyone have any other ideas that I could explore?

**Comment by KevinEady** [comment]
Hi @JckXia ,

Thanks for looking into this!

Looking at `test/index.js`, the log of "Running test async_worker" should come after the the Promise for the `async_progress_worker` test resolves. Since it's not, I think it is still `async_progress_worker` hanging. There could be some random deadlocking / mutex stuff going on when running the full test suite vs a subset of tests that makes it seem like everything is right when in actuality things are... not.

I remember awhile back we had a similar flakey test. It was due to the missing predicate condition for `condition_variable.wait()` calls: https://github.com/nodejs/node-addon-api/pull/1168 to fix this issue https://github.com/nodejs/node-addon-api/issues/1150 that has a very similar test timeout failure.

I noticed we have some places in `async_progress_worker` that use condition variables with no predicate, eg:
https://github.com/nodejs/node-addon-api/blob/0b53d885f50c83cd7cbcf505d3dcc89cf8c3d59f/test/async_progress_worker.cc#L38-L42

Maybe this is the cause? If you can start with addressing this one and see if it fixes the hang. If so, we should look into changing the other places that use condition variables with no predicate:

https://github.com/nodejs/node-addon-api/blob/0b53d885f50c83cd7cbcf505d3dcc89cf8c3d59f/test/threadsafe_function/threadsafe_function.cc#L92-L94

https://github.com/nodejs/node-addon-api/blob/0b53d885f50c83cd7cbcf505d3dcc89cf8c3d59f/test/typed_threadsafe_function/typed_threadsafe_function.cc#L88-L90

**Comment by JckXia** [comment]
Hey @KevinEady! Thank you, I added a wait condition and it indeed seems to have resolved the issue.
https://github.com/nodejs/node-addon-api/pull/1297
