### ISSUE TITLE
Missing napi_type_tag_object for Napi::External?

### ISSUE THREAD

**Issue by audetto** [nodejs/node-addon-api#1293]
https://github.com/nodejs/node-addon-api/pull/1261

This PR added support for `napi_type_tag_object`, but it did so for `Napi::Object`.
This API is mostly useful for `Napi::External`s which do no inherit from `Napi::Object`.

https://github.com/nodejs/node-addon-api/blob/b16c762a190ced903045aa15fbb910eee5c04a97/napi.h#L984-L991

Should this api be moved down to `Napi::Value`?

**Comment by audetto** [comment]
I can still call it but I need

`external.As<Object>().CheckTypeTag()`

which means the API works for things that are not just `Object`s.

**Comment by KevinEady** [comment]
Path forward:
1. Create a unit test in core that verifies that `napi_type_tag_object` and `napi_check_type_tag` can be used on externals. We expect this to work since a workaround was pointed out on https://github.com/nodejs/node-addon-api/issues/1293#issuecomment-1446171063 
2. If so, update the Node-API documentation for those two methods to say "The JavaScript object or external"

**Comment by audetto** [comment]
Although I can see a usage of tagging for any javascript value (a bit like using the topmost bits of a c pointer), for externals it is a question of life of segfault.

I think the underlying api should be way more strict

1. only create an external with a tag
2. only extract the `void *` if the tag matches

otherwise, how do I differentiate an external created by my library and one created elsewhere? and how do they do the same? probably a big security hole.

**Comment by gabrielschulhof** [comment]
Opened https://github.com/nodejs/node/pull/47141 for the core portion.

**Comment by gabrielschulhof** [comment]
@audetto type-tagging externals and wrapped objects is certainly a good practice. The problem is that type tags came along later than the wrapped objects and externals themselves. Thus, we can no longer go back and restrict their usage, because that would break all the code out there that already uses them, potentially unrestricted. We can certainly advocate for the usage of type tags so add-on authors eventually adopt the practice of type-tagging the pointers they expose to JS.

**Comment by audetto** [comment]
I full understand the constraints.
I think as well the lack of tags must be a source of many vulnerabilities.

**Comment by gabrielschulhof** [comment]
Fixed this in #1298. If you think more work needs to be done, please reopen this issue!
