### ISSUE TITLE
Consume async JS function by TypedThreadSafeFunction ?

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#1360]
Hello node-addon-api experts,

I use n-api to wrap 3rd party c++ library which receives async client requests, to be served by NodeJS.

For each request a c++ library spawns new thread and TypedThreadSafeFunction NonBlockingCall() is used to call NodeJS.

The client request is received in thread-unsafe [genericRequestHandler](https://github.com/SAP/node-rfc/blob/server/src/cpp/Server.cc#L287) and based on request the already existing TSFN instance is found as executed.

Client expects synchronous response, so after TSFN call invoked, the thread waits until the call is completed. Here the mutex and conditional variable are used:

- Lock after TSFN call: [lock](https://github.com/SAP/node-rfc/blob/server/src/cpp/Server.cc#L291)
- Unlock after thread-safe JavaScript function completed: [unlock](https://github.com/SAP/node-rfc/blob/server/src/cpp/Server.cc#L728)
- Lock/unlock implementation: https://github.com/SAP/node-rfc/blob/server/src/cpp/Server.h#L31

All works fine in this example when client request is served by JavaScript function [my_stfc_conection](https://github.com/SAP/node-rfc/blob/server/examples/server.js#L8).

My question is if async JavaScript functions can be also consumed by TSFN and how? 

To test, I first tried "brute force" delay, by calculations in loop. That works fine, n-api waits and receives correct result here:

```js
for (let i = 1; i < 1000000000; i++) x = i / 3;
```

When my_stfc_connection function declared async and `await` used instead of computations, the functions ends immediately and client receives no data:

```js
await delay(5))();
```

Is it possible to use async functions with TSFN as well  and how?

Feedback to design is welcome as well.

**Comment by mhdawson** [comment]
@KevinEady, @gabrielschulhof as our TFSN experts :)

**Comment by KevinEady** [comment]
I don't see why there would be a problem with using async functions in TSFNs. 

Async functions are just functions that _always_ return a promise. When creating the TypedTSFN, you pass in the async function. This function will be provided again in the `CallJs` (which is responsible for converting the native C++ `DataType` to Node-API values and calling the function).

In the [example](https://github.com/nodejs/node-addon-api/blob/main/doc/typed_threadsafe_function.md#example), where we call the function inside the `CallJs`:

```cpp
callback.Call(context->Value(), {Number::New(env, *data)});
```

This `Call` method will return an `Napi::Value` that is a promise (again, since async functions _always_ return a promise). So I imagine it's as simple as getting the `then` property (which is a function) and passing a handler to it as an argument. So maybe something like this:

```cpp
auto promise = callback.Call(....);

promise
    .As<Napi::Object>().Get("then").As<Napi::Function>()
    .Call(promise, {Napi::Function::New(env, NativeHandler)});
```

... where `NativeHandler` is some native C++ function for use within Node-API. The first argument passed to this function will be the promise's resolved value.

Some things to consider:

- You can pass arbitrary data to the native C++ function as the third parameter of the [`Napi::Function::New`](https://github.com/nodejs/node-addon-api/blob/main/doc/function.md#new) call, retrievable from the `Napi::CallbackInfo` via the [`Data()`](https://github.com/nodejs/node-addon-api/blob/main/doc/callbackinfo.md#data) method.
- Make sure to provide a promise rejection handler as well, either as a second argument to the `then()` call, or by making another function call to the promise's `catch()`.

Hope this helps! Let us know how it goes.

**Comment by bsrdjan** [comment]
Thank you @KevinEady, it almost works now 

Depending on server function result type, promise or data, the `processResultPromise` or `processResult` method is called.

In `processResultPromise` I am getting promise's resolved value but I could not figure out how exactly  to pass arbitrary data, as third parameter of `Napi::Function::New`here:

```c++
 jsf.Call(promise, {Napi::Function::New(env, processResultPromise)});
```

In `processResultPromise` I am missing DataType requestBaton and example where/how to pass that would help.

Here the context:

```c++

using DataType = ServerRequestBaton*;

void JSFunctionCall(Napi::Env env,
                    Napi::Function callback,
                    std::nullptr_t* context,
                    DataType requestBaton) {
  // ...
  Napi::Value jsResult = callback.Call({requestContext, abapArgs});
  // ...
  if (jsResult.IsPromise()) {
    // Server function returned promise
    Napi::Promise promise = jsResult.As<Napi::Promise>();
    Napi::Function jsf =
        promise.As<Napi::Object>().Get("then").As<Napi::Function>();
    jsf.Call(promise, {Napi::Function::New(env, processResultPromise)});
  } else {
    // Server function returned data
    processResult(env, jsResult, requestBaton);
  }
}

// Transform promise's resolved value to ABAP
Napi::Value processResultPromise(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  if (info[0].IsObject()) {
    Napi::Object jsResult = info[0].As<Napi::Object>();
    Napi::Array paramNames = jsResult.GetPropertyNames();
    uint_t paramSize = paramNames.Length();
    printf("\nparamSize %u", paramSize);
    for (uint_t i = 0; i < paramSize; i++) {
      Napi::String name = paramNames.Get(i).ToString();
      Napi::Value value = jsResult.Get(name);
      DEBUG(name.Utf8Value(), value.ToString().Utf8Value());
    }
  }
  return env.Undefined();
}

// Transform JS return value to ABAP
Napi::Value processResult(Napi::Env env,
                          Napi::Value jsResult,
                          DataType requestBaton) {
  Napi::Value errorObj = env.Undefined();
  Napi::Object params = jsResult.As<Napi::Object>();
  Napi::Array paramNames = params.GetPropertyNames();
  uint_t paramSize = paramNames.Length();

```

**Comment by bsrdjan** [comment]
It works now, as per this example [promise_callback_demo.cc](https://github.com/nodejs/node-addon-examples/blob/main/promise-callback-demo/node-addon-api/src/promise_callback_demo.cc#L54)

One detail in this example is unclear to me, why this comment " // TODO proper error handling (add failure handler)" when reject handler is provided as well? As 2nd arg of `then.Call(jsPromise,...`
