### ISSUE TITLE
Running single AsyncWorker at a time

### ISSUE THREAD

**Issue by vaguue** [nodejs/node-addon-api#1420]
Hello everyone,

I am working on a task where I want to perform multiple operations using AsyncWorker. However, I need to ensure that only one task is executed at a time, preferably while maintaining the order of tasks. I've had various ideas, such as creating an internal task queue in a separate C++ thread, or creating a queue for executing AsyncWorker tasks that would be updated from the OnOk method of the last executed worker. I would be very grateful for any advice.

Sincerely,
Seva D.

**Comment by legendecas** [comment]
You should be able to use a task queue on a separate thread and communicate with the JS thread with ThreadSafeFunction. 

Creating a queue for AsyncWorker execution is an option as well, but do note that an AsyncWorker should avoid endless blocks on its work because AsyncWorker utilizes uv's internal thread pool, which is used to run all file system operations, as well as `getaddrinfo` and `getnameinfo` requests.

**Comment by vaguue** [comment]
Actually I decided to use Node.js duplex stream to let the Node handle the queue part and made a JS wrapper around my asynchronous C++ method, so what du you think about this decision?

**Comment by legendecas** [comment]
I am not fully aware of your actual work that is performed in the queue so I can not assess the decision wisely. However, I would say that if the queue strategy provided by the stream API, or implemented in the JS rather than in the native add-on, it may be easier to maintain since the queue is only accessed by the JS thread.

I'm closing this since the question has been answered. Please let me know if there is anything else we should address.
