### ISSUE TITLE
AsyncProgressQueueWorker hangs on elements more than two

### ISSUE THREAD

**Issue by redplc** [nodejs/node-addon-api#1539]
I wrote a program to detect changes in the GPIO on the Raspberry Pi and to call a callback when a change occurs.
If I set up more than two watches, node.js hangs.
The function poll_gpio(event) waits for a change in the GPIO and return true for change and false for stop worker.
What could be the cause of this?

**Comment by KevinEady** [comment]
Hi @redplc ,

AsyncWorkers are backed by the libuv's `uv_work_t` with works on a [thread pool](https://docs.libuv.org/en/v1.x/threadpool.html):

> Its default size is 4, but it can be changed at startup time by setting the `UV_THREADPOOL_SIZE` environment variable to any value (the absolute maximum is 1024).

You can try changing the environmental variable and see if you get any change in results. Not sure why you're limited to two if the default is four? Maybe there are additional libuv workers running?

I would change your architecture to use an `std::thread` with a [thread-safe function](https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md). There are a few ways depending on your needs. Seems like you'd create a thread for each GPIO poll (since that blocks), but then either

1. Create a new thread-safe function for each thread, or
2. Create a single thread-safe function on addon initialization and share with each thread.

Question: how do you plan on interrupting the polling block?

Hope this helps!

**Comment by iiot2k** [comment]
Hello Kevin,
Thank you for your suggestion and for developing node-addon-api.
I fell into the UV_THREADPOOL_SIZE trap again.
The poll function is called in the poll_gpio function.
I use eventfd elements for the interruption.
If you want, I can send you the code.
I'll probably have to solve the problem differently now.

Viele Grüße aus Bremen
Derya

**Comment by iiot2k** [comment]
Solved with thread safe function.
Thanks to Kevin and everyone who helped.
Can be closed.

**Comment by redplc** [comment]
Closed
