### ISSUE TITLE
Discussion: ObjectWrap vs Externals

### ISSUE THREAD

**Issue by jgannon65** [nodejs/node-addon-api#1564]
First I want to thank everyone involved in this project, the quality of the code and documentation is very good.

I have a number of different questions about things, and ideally I would like to search a mailing list/ ask questions on a mailing list so I don't have to open a bunch of discussion issues. Is there a mailing list for this project?

Some of my questions are:
- When should ObjectWrap<T> be used instead of External<T>
- In the ObjectWrap<T> example a Reference is stored to the constructor, why is this necessary? It seems like the addon already stores the constructor in it's exports?
- It seems like it should be fairly common to use TypeTag in conjunction with ObjectWrap<T>, to ensure that a passed in parameter is of a certain type(calling Unwrap doesn't seem to do any type checking), is that true? 

Again, I'm sorry if these questions are answered elsewhere, I've tried to find answers in the documentation without success, please feel free to point me towards resources where some of these things are explained.

**Comment by KevinEady** [comment]
Hi @jgannon65 ,

We do not have any mailing list, but you can ask questions here if they are specific to node-addon-api / node-api, or more generally in the help repository: https://github.com/nodejs/help 

> When should ObjectWrap be used instead of External

- An `External` will not have any methods, members, etc. associated with it on the JavaScript side. This option may be better for a more functional/non-class approach, where you would return `Napi::External`s to JavaScript, pass that External as an argument to a node-addon-api C++ function, and cast the External to the correct type inside the C++ function. 
- An `ObjectWrap` will have its C++ instance methods associated with the JavaScript instance. This means the instance methods can access the instance members directly, without needing to do any special casting. You can see this in the [object wrap example](https://github.com/nodejs/node-addon-api/blob/main/doc/object_wrap.md#example), how `Example::GetValue` accesses `this->_value`.

> In the ObjectWrap example a Reference is stored to the constructor, why is this necessary? It seems like the addon already stores the constructor in it's exports?

The `exports` are returned to the JavaScript caller at the `require()` call site. Once the add-on's Init method returns the `exports`, it has no automatic/inherent access to these `exports`. If you want to construct an ObjectWrap instance inside C++, you need to call the constructor, which means a reference to it must be kept. That's what's happening in the [example](https://github.com/nodejs/node-addon-api/blob/main/doc/object_wrap.md#example)'s `Example::CreateNewItem`.

> It seems like it should be fairly common to use TypeTag in conjunction with ObjectWrap, to ensure that a passed in parameter is of a certain type

Type tags can be used on any "type-taggable" C++ object, which are `Napi::Object` and `Napi::External`:

- For `ObjectWrap`'d objects, you have a little more flexibility, since the class instance methods would be associated with the C++ `this` inheriting from `Napi::ObjectWrap<T>`.
- Type tags are pretty much required when using multiple types of `External<T>`s in your project, as you would need to differentiate between different `T`s. 

When using type tags, you can have some static list of `napi_type_tag`s, one for each type `T`, and when creating the object, assign the type tag, and use `CheckTypeTag` prior to doing any sort of casting. 

> ... (calling Unwrap doesn't seem to do any type checking), is that true? 

There is _some_ type checking in `Unwrap` on the native Node-API side. For example, if you try to call a ObjectWrap instance method with an incorrect JavaScript `this`, you'll get an `Illegal invocation` error:

```
> foo = new x.objectwrap.Test()
Test [TestTag] { ownProperty: [Getter], ownPropertyT: [Getter] }
> foo.testMethod("foo")
'foo instance'
> foo.testMethod.call({}, "foo")
Uncaught TypeError: Illegal invocation
```

Hope this helps! Let us know if you have any additional questions. If not, please feel free to close this issue.

**Comment by jgannon65** [comment]
Thank you so much for your help, and quick response.
