### ISSUE TITLE
[question] How to bind function to certain object?

### ISSUE THREAD

**Issue by frabert** [nodejs/node-addon-api#204]
I would need the ability to create an object value in C++ and a number of functions, all of which need to be bound to said object, something like this:

````js
let obj ={}
let f = function() { this.x + 2 }

obj.f = f.bind(obj)
````

How can I achieve this effect? Otherwise, is there an easier way to create OOP-style objects, _without the need of creating a constructor?_ i.e. I need these objects to only be able to be created from the C++ interface.

**Comment by NickNaso** [comment]
I don't know if I understand but do you want export something like that from C++?
```js
{
  f: function f() {},
  g: function g(){}
 .....
}
```

**Comment by frabert** [comment]
Yes, and those functions need `this` to be bound to the object itself

**Comment by NickNaso** [comment]
Ok I will try to find a solution in the mean time you can take a look at the following examples if you didn't see yet:
https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/4_object_factory/node-addon-api
https://github.com/nodejs/abi-stable-node-addon-examples/tree/master/6_object_wrap/node-addon-api

**Comment by frabert** [comment]
The "object factory" is what I am currently using for "plain" objects, while the object wrapper forces me to provide a constructor, that I don't want to expose.

**Comment by guymguym** [comment]
@frabert Just wondering - why do you need the functions to be bound to a specific object?
If you use napi to create a function and then simply assign it to the object then calling it "through" the object will have this assigned to the object.

For example:
```
Napi::Value
foo(const Napi::CallbackInfo& info)
{
  Napi::Env env = info.Env();
  Napi::Object self = info.This().As<Napi::Object>();
  int x = Napi::Value(self["x"]).As<Napi::Number>();
  return Napi::Number::New(env, x + 2);
}

Napi::Object
createObject(const Napi::CallbackInfo& info)
{
  Napi::Env env = info.Env();
  Napi::Object obj = Napi::Object::New(env);
  obj["x"] = Napi::Number::New(env, 2);
  obj["f"] = Napi::Function::New(env, foo);
  return obj;
}
```

Then if you export `createObject` from your addon and call it from JS you will get an object looking like this:
```
const obj = createObject();
// essentially returns an object equivalent to:
// {
//   x: 2,
//   f: function foo() { return this.x + 2 }
// }
assert(obj.f() === 4);
obj.x = -2;
assert(obj.f() === 0);
```

However this is not like `bind` since if you call `f()` through another object or no object at all then it will change the value assigned to `this` in the native function:
```
const devil_obj = { x: 664, f: obj.f };
assert(devil_obj.f() === 666);

const f = obj.f;
f(); // error, this is undefined
```

Is that what you mean or you specifically need to bind the function to one object for good?

**Comment by frabert** [comment]
@guymguym This seems to be what I need! Thanks!
