### ISSUE TITLE
Support for npm@3 installation issues?

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#306]
Experiencing issues with npm install of my N-API addon, only with nodejs 6 (both Windows and Linux), I created an issue for NPM: https://npm.community/t/enotempty-directory-not-empty-rename-on-nodejs-6-only/513/2

According to response, the npm@3 ([node 6.x standard](https://nodejs.org/en/download/releases/)) is not "really supported" and according to #302 only security fixes are provided.

If the addon is declared supported on node 6.x, the installation via standard npm is expected to work as well.

Would it be possible to get more support for this particular issue or provide support for installation issues in general, in such cases?

**Comment by mhdawson** [comment]
Have you tried reaching out to the maintainer for the module?  While N-API allows modules owners to support modules that can run with multiple versions of Node.js, it is still up to the module owner to declare support for different versions and avoid things that may cause problems.  Unless I'm misunderstanding in this case the problem is an interaction between one of the dependencies and a module not related to N-API?

**Comment by bsrdjan** [comment]
Yes and the maintainer clarified [only the latest npm version is supported](https://npm.community/t/enotempty-directory-not-empty-rename-on-nodejs-6-only/513/4), was new to me.

It seems I need npm@latest added under `peerDependency` or `engine` section of my `package.json`, need to check if any difference.

It is not an N-API issue and can be closed IMHO.
