### ISSUE TITLE
Are STL smart pointers supported?

### ISSUE THREAD

**Issue by BotellaA** [nodejs/node-addon-api#313]
I am doing some exploratory work on N-API. I did'nt see any usage of STL smart pointer in any example. Is it a limitation of the api of something deeper?

I would like to wrap code like this:
```
class Object {
public:
    static std::unique_ptr<Object> create();
};
```

Do you have any recommandation?
Thanks a lot for your help!

**Comment by NickNaso** [comment]
Hi @BotellaA ,
I think that you want use smart pointer to reference object and manipulate its lifetime. To accomplish at this you need to use `Reference` class see:  **[Reference documentation](https://github.com/nodejs/node-addon-api/blob/master/doc/reference.md)**.

In general a variable is available until the end of the execution of the function, after that it is eligible to be garbage collected. To avoid this behavior you need to store the value on a reference. 
In general you cannot simply use a pointer because the normal lifespan correspond to a single native method invocation.
The JavaScript engine will garbage collect the variable that you point and you will obtain random data because of the garbage collector process.

**Comment by BotellaA** [comment]
Thanks, it looks like this is what I want. I will try it.
