### ISSUE TITLE
Remove outdated Doxygen doc

### ISSUE THREAD

**Issue by mhdawson** [nodejs/node-addon-api#368]
We have not kept it up to date and we have full coverage in our other doc, so remove it.

**Comment by NickNaso** [comment]
Hi everyone,
I think that we think to take a decision about the **gh-pages** branch of this repo. Now it contains the old documentation  created by Docygen, but this documentation is not updated form the begin of July.
About that I have 3 proposals:
* Drop the old documentation and disable the **gh-pages**
* Continue to update the documentation generated by Doxygen
* Use **gh-pages** to better advertise **node-addon-api** and in general **N-API**. We could use tools like Gatsby and create a simple web site exposed by the **gh-pages**. In the  web site I would like to expose the new markdonwn documentation and other useful resources like materials of workshop and talks that we did.
I think that we can talk about this at Node.js Collaborator Summit.

**Comment by NickNaso** [comment]
At Node.js Collaborator Summit we discussed about the idea to expose the documentation through the GitHub pages like a web site.
For the occasion I created a mock-up to better explain the idea. I attached the screenshot in this issue remembering that it’s a prototype and we need working on it to arrive at final version.
<img width="1286" alt="screenshot 2018-10-15 at 17 44 01" src="https://user-images.githubusercontent.com/387506/46986016-0d3a3d00-d0a2-11e8-8379-50c377f73112.png">
<img width="1287" alt="screenshot 2018-10-15 at 17 44 14" src="https://user-images.githubusercontent.com/387506/46986018-13c8b480-d0a2-11e8-9656-bc33336d7886.png">
<img width="1283" alt="screenshot 2018-10-15 at 17 44 32" src="https://user-images.githubusercontent.com/387506/46986020-16c3a500-d0a2-11e8-8588-9b1b1936144f.png">

I proposed to expose our markdown documentation through the web site together with some other resources that now we have to advertise if we want to increase the adoption of **node-addon-api** and **N-API**.
Now we have al the materials produced to create the **N-API workshop** and **slides** and **videos** of talks that members of the team did in this year. 
In the discussion it turns out that other than the markdown documentation we need to provide a **reference of the API** like V8, so we will have the documentation and a reference of the API that will cover all the developers’ needs.
From my perspective this will be a long term project now I will start on create what I proposed on my own then I will present to you the result and after some iterations we  will must to start thinking on how we want organize everything.
Please if someone have some other ideas I  will be happy to discuss on this issue or in the next N-API team meeting.

**Comment by NickNaso** [comment]
Hi everyone,
I want start working on this and pass from design to a real prototype, but for me it could be great if you post useful resources that you want add to the "web site" so I can organise all for the best. 
In the specific I need links yo articles, video (talks), slides and any useful resource that we can use to improve our evangelism activity.

**Comment by mhdawson** [comment]
From Node+JS Interactive: https://www.youtube.com/watch?v=BrJcsYjp8Nw

**Comment by mhdawson** [comment]
From Node Summit: https://github.com/mhdawson/presentations/blob/master/2018/NodeSummit2018%20-%20Building%20Next%20Generation%20add-on%20modules%20for%20Node.js%20using%20N-API.pdf

**Comment by romandev** [comment]
I'm not sure if this slide is helpful to you but anyway I'll share it.
https://docs.google.com/presentation/d/10RCRnKXHUJBl-Pe_LfB-5Uhd0ADhcvSR5978-7ckzWQ/edit?usp=sharing

**Comment by mhdawson** [comment]
@romandev thanks for that link, looks like a good deck.  We should get you to give us an update on how the webidl generator is going at some point.

**Comment by NickNaso** [comment]
What do you think if we add something about the N-API badges in the web site for the documentation?
See: **[https://github.com/nodejs/node-addon-api/issues/334](https://github.com/nodejs/node-addon-api/issues/334)**

**Comment by mhdawson** [comment]
Makes sense toi me.

**Comment by mhdawson** [comment]
We have not had progress on a new site and the Doxygen is long out of date so I went ahead and deleted the gh-pages branch which disables the publishing of the stale Doxygen, closing.
