### ISSUE TITLE
OSX addon wrapper, build and deploy 

### ISSUE THREAD

**Issue by bsrdjan** [nodejs/node-addon-api#378]
Building a node addon wrapper of external binary C++ library on OSX, I have following question (#370 follow-up).

The main external binary lib (with few child libs) can't be shipped with my node wrapper.

The user must download and install it separately, let say in `/usr/local/external/lib` folder.

After the `npm install node-wrapper` installs my wrapper, my expectation was if the user set DYLD_FALLBACK_LIBRARY_PATH or DYLD_LIBRARY_PATH to `/usr/local/external/lib` for example, my wrapper will find and load the external lib.

It took me a day to find out why it sometimes works (e.g. `node test1.js`) and sometimes not (`mocha`, `node-pre-gyp testbinary` ...). When a subprocess started on macOS, these DYLD* shell variables are deleted from subprocess context, as explained [here](https://github.com/rbenv/rbenv/issues/962#issuecomment-275843624) and in [mocha/issues/3392](https://github.com/mochajs/mocha/issues/3392). Reading this, it seems that using these variables could lead to more problems than solving them on macOS, what is probably the reason why they are initially not set and not used in standard image.

Which approach the other projects here follow in building and deploying external lib wrappers on macOS ?

What could be optimal solution in my case, when the wrapper does not know in advance the location of external lib ? On Windows, setting PATH is enough, on Linux the so.conf and ldconfig but what to do on macOS?

**Comment by NickNaso** [comment]
Hi @bsrdjan,
I'm not a great expert, but what I try to do every time I have to implement new native add-on is to ship it without external dependencies. It's a long process because the C / C++ libraries that I have to integrate don't use **GYP**, but at the end you have a native add-on that you can deliver every platform / architecture (VPS, Container, Serverless). 
I know that sometimes you cannot follow this approach and in the past I used environment variables to set the path where your library is located. So if you are a user that use the add-on  you have to install the library and then set the environment variable that point to the library. You can use the environment variable from **binding.gyp** file. Another solution is to use **pkg-config** utility (See: [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/)) to retrieve the libraries that I want and in the bindig.gyp I do something like this:
```js
"libraries": [
    '<!@(pkg-config --libs your-library)',
    #...
],
```
On the **node-gyp** repo you can find solutions that other developers used to create their **binding.gyp**. It was very useful to me in the past. 
**[https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild](https://github.com/nodejs/node-gyp/wiki/%22binding.gyp%22-files-out-in-the-wild)**.
Hope to be helpful.

**Comment by mhdawson** [comment]
@bsrdjan did @NickNaso's answer solve your question?

**Comment by bsrdjan** [comment]
I could not apply pkg-config in my use-case. To my understanding, it simplifies the build process and my problem is shipping an nodejs addon, depending on binary libraries which must be download and installed separately, so their path may differ on macOS systems of node addon users.

For the time being I provide a shell script to "patch" the binaries and node addon, by adding that "remote path" (macOS term) to binaries and to node addon, after the installation, so they can find each other. Done atm manually, could be automated by npm postinstall script.

Thank you for the suggestion, it  helped to further analyse the problem and binding.gyp examples are great resource. I suppose the issue can be closed..
