### ISSUE TITLE
Nan::Persistent<TYPE> should be converted to Napi::ObjectReference::Persistent

### ISSUE THREAD

**Issue by nikita-malyschkin-work** [nodejs/node-addon-api#392]
While using the conversion tool, we discovered that `Nan::Persistent` is not properly converterted to `Napi::ObjectReference::Persistent`.

```cpp
// what we had
Nan::Persistent<String> send_callback_symbol;

// what we got
Napi::Persistent<String> send_callback_symbol;

// what we wanted
Napi::ObjectReference::Persistent<String> send_callback_symbol;
```

**Comment by DaAitch** [comment]
@nikita-malyschkin-work did you mix up something?
`Napi::Persistent(...)` is a function not a type and there is no `Napi::ObjectReference::Persistent`.

```cpp
Napi::ObjectReference obj_ref = Napi::Persistent(obj);
Napi::FunctionReference func_ref = Napi::Persistent(func);
Napi::Reference<Napi::String> str_ref = Napi::Persistent(str);
```

can you check, what you've pasted.

**Comment by gabrielschulhof** [comment]
@nikita-malyschkin-work N-API does not allow one to create persistent references to strings. So, while `Nan::Persistent<v8::String>` is possible, `Napi::Persistent<Napi::String>` is not, because the core N-API does not allow one to create a reference to a string.

The reason for this is that, unlike V8, N-API is engine-agnostic, and AFAIK V8 is the only engine that supports persistent references to strings.

In this case, I believe your best bet would be to convert to a native string, and store a pointer to the native string instead.

**Comment by mhdawson** [comment]
I'm going to close this since its been a long time since Gabriel's last response/suggestion. Please let us know if you think that was not the right thing to do.
