### ISSUE TITLE
how to send data continually to javascript from windows Wave API callback function?

### ISSUE THREAD

**Issue by CTianXing** [nodejs/node-addon-api#406]
sorry for my poor english, hope you understand what I mean.
I take the windows Wave API to record sound and send it to speech recognize. There is a callback  in the waveInOpen(), i can take the buffer recorded to recognize and get the result continually,but how do i send the result to javascript in the waveInProc(). 
MMRESULT waveInOpen(
   LPHWAVEIN       phwi,
   UINT            uDeviceID,
   LPCWAVEFORMATEX pwfx,
   DWORD_PTR       dwCallback,
   DWORD_PTR       dwCallbackInstance,
   DWORD           fdwOpen
);
void CALLBACK waveInProc(
   HWAVEIN   hwi,
   UINT      uMsg,
   DWORD_PTR dwInstance,
   DWORD_PTR dwParam1,
   DWORD_PTR dwParam2
);
I try to emit events from addon, it has error"Entering the V8 API without proper locking in place“. I don't know how to use Asynchronous Thread-safe Function Calls and if it works. So I'm here for help. Thank you.
[record2recognize.txt](https://github.com/nodejs/node-addon-api/files/2651865/record2recognize.txt)

**Comment by NickNaso** [comment]
Hi @CTianXing,
sorry for the late in the answer. I taken a look at your code and I think that you are able to emit the first event that you named **"start"** but the problem is that you cannot able to emit the **"data"**.
Is is right?  You need to preserve the instance of the emit function and store it on a `Napi::FunctionReference` see the documentation here:  https://github.com/nodejs/node-addon-api/blob/master/doc/function_reference.md.
In alternative you can extend the `EventEmitter` like in this example:
https://github.com/nodejs/node-addon-examples/tree/master/inherits_from_event_emitter/node-addon-api
I hope that the informations that I provided is good for you otherwise don't esitate to reply.

**Comment by gabrielschulhof** [comment]
@CTianXing @romandev is [working on](https://github.com/nodejs/node-addon-api/issues/312#issuecomment-446281135) providing a C++ wrapper for [napi_threadsafe_function](https://docs.nodejs.org/dist/latest-v10.x/docs/api/n-api.html#n_api_asynchronous_thread_safe_function_calls). In the meantime, you can use the C API directly.

At any rate, you should replace
```C++
Napi::Function cbemit;
```
with
```C++
napi_threadsafe_function cbemit;
```
which you then create using `napi_create_threadsafe_function()`. If you know ahead of time how many threads will be calling the function, you can set the `initial_thread_count` at creation time. Then, in the thread that is supposed to emit the `"data"` event you call `napi_call_threadsafe_function()`.

Realize though that this calls a JavaScript function rather than emitting a JavaScript event. However, in your `call_js_cb` you have a chance to run any kind of code you like, including emitting an event.

**Comment by CTianXing** [comment]
@NickNaso @gabrielschulhof Thank you very much!
I implemented it with "async_work_thread_safe_function". Wave API usually deal data in the CALLBACK waveInProc,but napi_call_threadsafe_function must be used in the ExecuteWork,is that right? so I preserve the result to global in waveInProc ,then I call napi_call_threadsafe_function in the ExecuteWork once a second. It works,I can get the result continually in javaScript.
I'm a new programmer, and I appreciate your help.

**Comment by gabrielschulhof** [comment]
@CTianXing sounds like you're using `napi_threadsafe_function` correctly👍 `napi_call_threadsafe_function` can be called from any thread.
