### ISSUE TITLE
Equivalent to Nan::Persistent<v8::String>

### ISSUE THREAD

**Issue by maierfelix** [nodejs/node-addon-api#443]
Hi, I'm trying to add a persistent reference to a javascript string in my class like this:

````cpp
..
class _Test: public Napi::ObjectWrap<_Test> {
  Napi::Reference<Napi::String> name;
}

void _Test::SetName(const Napi::CallbackInfo& info, const Napi::Value& value) {
  Napi::Env env = info.Env();
  this->name.Reset(value.ToString()); // error: An object was expected
}
````

````js
let t = new Test();
t.name = "1234";
````

I tried `ObjectReference` as well, but get the same error, what am I missing?

Thanks

**Comment by gabrielschulhof** [comment]
@maierfelix N-API does not support references to primitive types, because engines other than V8 do not support them. If you want to store a primitive string, you must store it as a `char*` and then convert it back to a JavaScript string by creating a new JavaScript string.

Out of curiosity, what is your use case for storing a persistent reference to a string?

**Comment by maierfelix** [comment]
Thanks for clarifying! I need to convert a large code generator which currently emits v8 code over to napi and was just fiddling around to collect the differences

**Comment by jaubourg** [comment]
@gabrielschulhof I'm hitting the same issue. I'd like to keep the reference to the underlying `const char *` alive for the duration of an AsyncWorker so that I can inspect the value in another thread. No cigars because of this Reference limitation. When Execute starts, there's only garbage in of course. I actually have to duplicate the buffer and free it in the destructor of the AsyncWorker. Pretty inconvenient if you ask me.

**Comment by gabrielschulhof** [comment]
@jaubourg we couldn't support references to primitive types because not all engines support such references.

AFAIK accessing a JavaScript value from another thread is not supported in V8 either, so that would include dereferencing a persistent reference to a string.

You can save yourself the allocation/destruction by adding a `std::string` member to your class and storing the string in there. It's still a copy, but at least it doesn't require explicit memory management. `Napi::String` conveniently casts implicitly to `std::string`:
```C++
Napi::Value SomeBinding(const CallbackInfo& info) {
  std::string something = info[0].As<Napi::String>();
}
```

**Comment by mhdawson** [comment]
@gabrielschulhof I was just about to suggest something along the same lines :)

**Comment by jaubourg** [comment]
Thanks for the tip @gabrielschulhof :) It just saddens me any time there unnecessary allocation and duplication of memory :(
