### ISSUE TITLE
Buffer::New finalizeHint clarification needed

### ISSUE THREAD

**Issue by kevinGodell** [nodejs/node-addon-api#447]
I was able to successfully create a buffer from external data inside the AsyncWorker. The array is created on the heap inside Execute() and the Buffer::New is created from the array in OnOK() before being passed in the callback. I have also verified that the finalizeCallback function gets called when node runs garbage collection.

I can't understand what the finalizeHint does. Looking at the tests run on [buffer.createExternalBufferWithFinalizeHint()](https://github.com/nodejs/node-addon-api/blob/master/test/buffer.js#L56), I see that the hint passed to the function is `char* hint = nullptr;` 

Relevant part of my code is https://github.com/kevinGodell/pam-diff/blob/draw-bounding-box/src/async.cc#L295 and https://github.com/kevinGodell/pam-diff/blob/draw-bounding-box/src/results.cc#L131

As always, any help or advice is appreciated.

**Comment by legendecas** [comment]
The hint is used as an additional argument on finalization. In some cases it might not be possible to determine what's else that is related to the data pointer since *it's underlying memory would be overwritten*. Thus an additional arbitrary hint that could indicates *how the data pointer could be released* is helpful in the case.

**Comment by kevinGodell** [comment]
@legendecas Thanks for taking the time to respond. I do appreciate any feedback. Forgive me for not being very clear on my initial request. 

What does the hint do, other than giving a hint? What type of information should be given in the hint? Do I have to handle the hint in the finalizeCallback or is that something that happens `automagically` in the node-addon-api/n-api layer? Are there any real world uses of this that I may inspect? The buffer test that used a nullptr as the hint didn't enlighten me on its practical usage.

As a side not, my code works OK without using the hint. I am just trying to explore if there is any added value by passing additional data to the api.

**Comment by legendecas** [comment]
> What does the hint do, other than giving a hint?

```c++
uint16_t* data = new uint16_t[testLength];

char* hint = nullptr;
Buffer<uint16_t> buffer = Buffer<uint16_t>::New(
  info.Env(),
  data,
  testLength,
  [](Env /*env*/, uint16_t* finalizeData, char* /*finalizeHint*/) {
    delete[] finalizeData;
  },
  hint);
```

`uint16_t* data = new uint16_t[testLength]` doesn't require any additional hint to free `data` since it could be freed directly with `delete`. 

```c
struct ComplexStruct {
  // ...some fields
  uint16_t data[20];
  // ...other fields
};

ComplexStruct* aComplexStruct = new ComplexStruct;

Buffer<uint16_t> buffer = Buffer<uint16_t>::New(
  info.Env(),
  aComplexStruct->data,
  20,
  [](Env /*env*/, uint16_t* finalizeData, ComplexStruct* hint/*finalizeHint*/) {
    delete hint;
  },
  aComplexStruct);
```
If we used `aComplexStructPointer->data` as the buffer's data pointer, the data pointer could not be freed directly without knowing where `ComplexStruct` is. With an additional hint parameter, finalizers are able to properly release `data` with `aComplexStruct`.

> What type of information should be given in the hint?

That depends. In the case about, it could be `ComplexStruct*`.

> Do I have to handle the hint in the finalizeCallback or is that something that happens `automagically` in the node-addon-api/n-api layer?

Hints have to be used in your finalizer implementation. Or it doesn't make any difference.

There is nothing happens automatically or magically AFAIK :)

> The buffer test that used a nullptr as the hint didn't enlighten me on its practical usage.

The buffer test is the first case above. It doesn't require an additional hint to tell how to release the data. Thus a nullptr is enough there.

**Comment by kevinGodell** [comment]
@legendecas That is an awesome explanation. It is very clear and concise. Thank you for taking the time to help.
