### ISSUE TITLE
Bundles node_api.h is outdated

### ISSUE THREAD

**Issue by extmchristensen** [nodejs/node-addon-api#463]
I am writing a large C++ addon and would like to use the node-addon-api but it lacks some of the "C" API's features (thread safe functions in particular) so I need to fallback on the "C" N-API. 

Unfortunately, the node-addon-api bundles a too old version of "node_api.h", so I can't mix and match.

Could node-addon-api be updated to use latest N-API C header files ?

**Comment by legendecas** [comment]
AFAIK, you could directly include `node-api.h` in `/usr/local/include/node` (assuming installed node.js with headers).

**Comment by extmchristensen** [comment]
@legendecas But I would like to do this in a platform independent way (that also works on Windows).

**Comment by extmchristensen** [comment]
@legendecas Also, I suspect the linker might yield problems if the same c++ code is using two different versions of the same header file in the same build ?

**Comment by gabrielschulhof** [comment]
@extmchristensen you only need the bundled N-API implementation if you're planning on building against a version of Node.js which does not itself have an implementation of N-API (i.e. pre-6.14.2, IIRC). node-addon-api avoids using the built-in headers if the version of Node.js against which it's building has its own headers.

The reason node-addon-api does not have thread-safe function is not that it's missing from the bundled headers, but that it hasn't been implemented in the C++ wrapper – however, as you noticed, we have https://github.com/nodejs/node-addon-api/pull/442 that seeks to implement it.

**Comment by extmchristensen** [comment]
@gabrielschulhof I don't understand  the point that node-addon-api is unneeded for recent node versions.... If I don't add node-addon-api to package.json + binding.gyp, I get compilation errors about napi.h being missing.

**Comment by gabrielschulhof** [comment]
@extmchristensen  node-addon-api is needed if you wish to use `Napi::*` in your native addon. On recent versions of Node.js, `src/node_api.h`, `src/node_api.cc` and all other files under node-addon-api's `src/` directory are unneeded, because they are part of Node.js itself.

What versions of Node.js do you plan to support with your native addon?

**Comment by extmchristensen** [comment]
@gabrielschulhof On my node 11 windows installation, I can not find the headers in the node installation. itself, but they are present under node-gyp at  <homedir>\.node-gyp\version\include\node

As for your question, I need to support at minimum v10 and v11 with additional support for v8 and v9 as nice to have. I am currently using the C++ node-addon wrapper + a 3rd party napi-thread-safe-callback library to allow async callback from 3rd party thread.

**Comment by gabrielschulhof** [comment]
@extmchristensen for this range of Node.js versions N-API is built-in. Therefore node-addon-api will not compile the version of N-API it ships. This means that the files in its `src/ ` subdirectory are OK to be out-of-date because they will not be compiled and linked into your add-on. Rather, your addon will link to the N-API implementation provided by Node.js.

**Comment by gabrielschulhof** [comment]
This issue, along with #509 needs to be closed when Node.js v8.x goes out of scope and we will have removed the src/-provided implementation of N-API.
