### ISSUE TITLE
Napi::Object in AsyncWorker

### ISSUE THREAD

**Issue by daihy8759** [nodejs/node-addon-api#468]
```
// in callback
	Napi::Object config = info[0].As<Napi::Object>();
	Napi::Function cb = info[1].As<Napi::Function>();
	(new ScanAsyncWorker(cb, config))->Queue();
// in worker
public:
	ScanAsyncWorker(
		const Napi::Function &callback,
		const Napi::Object config)
		: Napi::AsyncWorker(callback), scanConfig(config)
	{
	}
```
i  get nothing from scanConfig，anything wrong？

**Comment by gabrielschulhof** [comment]
@daihy8759 what do you mean "i get nothing from scanConfig"?

**Comment by daihy8759** [comment]
scanConfig.Get("xx") is undefined

**Comment by gabrielschulhof** [comment]
@daihy8759 AFAICT that can only happen if you haven't defined the `"xx"` property on the JavaScript side before passing `scanConfig` into the binding. Can you check that `"xx"` is set on the object in JavaScript?

**Comment by daihy8759** [comment]
yes

**Comment by gabrielschulhof** [comment]
@daihy8759 you should also be able to retrieve `"xx"` in the constructor for the `ScanAsyncWorker` class.

If you want to access `scanConfig` and its properties from the `OnOK` and/or `OnError` callbacks of the `ScanAsyncWorker` class, you must store `scanConfig` as a `Napi::ObjectReference`, not a `Napi::Object`, because a `Napi::Object` becomes invalid as soon as control returns to JavaScript, whereas a `Napi::ObjectReference` remains valid until you delete it.

**Comment by mhdawson** [comment]
I'm going to close this as its been a long time since Gabriel's last suggestion. Please let us know if you think that was not the right thing to do.
