### ISSUE TITLE
Feature Request: Support for Map and Set

### ISSUE THREAD

**Issue by markandrus** [nodejs/node-addon-api#472]
I'm converting a module from v8/NAN to N-API/node-addon-api and it would be very useful to have support for Map and Set. I see I can get Map's constructor from `env.Global()`, but first-class support would be nice. Perhaps this should first be added to/requested from N-API first?

**Comment by gabrielschulhof** [comment]
@markandrus we can consider adding them to N-API and then to node-addon-api.

**Comment by gabrielschulhof** [comment]
@markandrus in our working group we've recently discussed exposing various additional features as C++ addons and concluded that an ecosystem of modules would be the best approach. Thus, if you wish to expose `Map` and `Set` using the global constructor, please feel free to contribute the code as an npm module. We would then be happy to include a pointer to your code from this repo.

Later, if it turns out that there is broad demand for your module, we would be happy to consider adding it to this repo, and we could further look into exposing the engine's `Map` and `Set` APIs via N-API, especially if performance becomes a concern.

**Comment by markandrus** [comment]
Thanks, @gabrielschulhof — I probably can't release such a module right now, but if anyone else encounters this issue they can take a look at my functions `CreateMap` and `SetMap` [here](https://github.com/node-webrtc/node-webrtc/blob/v0.4.0-beta1/src/dictionaries/webrtc/rtc_stats_report.cc#L13).

**Comment by mhdawson** [comment]
@markandrus I think this can be closed now?

**Comment by markandrus** [comment]
Yes, fine by me.
