### ISSUE TITLE
Nan:AsyncProgressWorker equivalent?

### ISSUE THREAD

**Issue by JipBoesenkool** [nodejs/node-addon-api#473]
@jasongin could you reply to @ptgolden's  question? I can find neither node-addon-api or n-api functions to implement `streaming worker` such as  [Nan::AsyncProgressWorker](https://github.com/nodejs/nan/blob/master/doc/asyncworker.md#api_nan_async_progress_worker)

There is example of usage from a book: [factorization example | https://github.com/freezer333/nodecpp-demo/blob/master/streaming/examples/factorization/factorization.js]. 

In my case I need to hook some system events and pass them to js callback.

_Originally posted by @gorshkov-leonid in https://github.com/nodejs/node-addon-api/issues/75#issuecomment-441468273_

**Comment by JipBoesenkool** [comment]
I have exactly the same use case as @gorshkob-leanid

**Comment by mhdawson** [comment]
@JipBoesenkool have you looked at the https://nodejs.org/api/n-api.html#n_api_asynchronous_thread_safe_function_calls as an option?  Not sure if that will work for your use case but worth a look.

**Comment by gorshkov-leonid** [comment]
I tried napi and it, it works. But it looks redundantly. Nan API is much more convenient in this case.

**Comment by gorshkov-leonid** [comment]
To clarify case, I use system hook with own callback. So I need to pass values from this callback to js side. The code might be not pretty, because I have to recall(=learn) c++ basis after ages of oblivion:

https://github.com/gorshkov-leonid/node-native-addons-example/blob/master/native-addon-get-processes/WindowListFunctions.cc
