### ISSUE TITLE
Is it possible to create a new Env()/isolate in async worker

### ISSUE THREAD

**Issue by garrensmith** [nodejs/node-addon-api#525]
Hi,

Thanks for the great work on `node-addon-api`. It is really nice to work with.
I want to check if it's possible to create a new v8 isolate inside an AsyncWorker or if I could create a new Env()/Isolate and pass it to an AsyncWorker.

**Comment by NickNaso** [comment]
Hi @garrensmith,
when you create an `Napi::AsyncWorker` it automatically store the  environment in which it has been created. You can retrieve the stored `Napi::Env` using the method `Napi::AsyncWorker::Env()`.

**Comment by garrensmith** [comment]
Awesome. Is that a completely new environment or the same environment that the main thread is using? I want to create a completely new clean environment


________________________________

**Comment by KevinEady** [comment]
@garrensmith can you elaborate by what you mean by "completely new environment" and what your use-case is? Your addon really shouldn't need to care about how the Environment is being managed.

**Comment by garrensmith** [comment]
@KevinEady I'm looking at using it for CouchDB. We have a situation where we run unknown user javascript code. So for security reasons, we need to run it in a different isolate and context so that it does not have access to general scope and instead is heavily locked down.

**Comment by gabrielschulhof** [comment]
@garrensmith creating a new Node.js environment is currently outside the scope of N-API. Also, creating a new Node.js environment for security purposes leads to a false sense of security, because it runs in the same process as the trusted Node.js environment and therefore shares a bunch of resources, like open file descriptors.

Isolation of Node.js environments in general is beyond the scope of Node.js itself. AFAIK (and I'm nowhere near an expert on the matter) the safest way to isolate untrusted Node.js code is by launching a second Node.js process, sandboxed using things like a containerization.

**Comment by garrensmith** [comment]
@gabrielschulhof right the best seems to be a new process. But a new isolate is at least better than in the same isolate. Thanks for the information everyone that helped on this issue. It is really appreciated.
