### ISSUE TITLE
Error was ignored if `ThreadSafeFunction::GetContext()` failed

### ISSUE THREAD

**Issue by legendecas** [nodejs/node-addon-api#581]
Currently `napi_status` was ignored in `ThreadSafeFunction::GetContext()`. No `napi_status` shall be ignored as it would unstablize the behavior we'd expect.

Since the function signature doesn't support error returning, an alternative might be aborting on non-`napi_ok` statuses.

_Originally posted by @legendecas in https://github.com/nodejs/node-addon-api/pull/546_

**Comment by KevinEady** [comment]
Hi team,

I can start work on this if nobody has? (direct ping to @legendecas since he reported this)

**Comment by legendecas** [comment]
@KevinEady You have it. :P

**Comment by legendecas** [comment]
I think aborting would be just fine. Since we don't expect any error on this method. Neither do we have any recover solution on the error situation. Try `NAPI_FATAL_IF_FAILED`.

**Comment by gabrielschulhof** [comment]
Looking at the implementation, `napi_get_threadsafe_function_context()` will only fail if one of the parameters passed in is `NULL`. So, since both parameters are under our control, it should never fail – unless, in the future, we introduce some new failure mode, in which case the abort should be perfect.
