### ISSUE TITLE
Add Object::New() taking a list of properties

### ISSUE THREAD

**Issue by dmitryash** [nodejs/node-addon-api#603]
Example:

```cpp
static Object New(
    napi_env env, ///< N-API environment
    const std::initializer_list<PropertyDescriptor> &properties  ///< initial prperties
);
```

**Comment by NickNaso** [comment]
I don't know if we can do this because to create a `Napi::PropertyDescriptor` accessor we need the object on which the accessor will be defined. So the actual workaround is:
- Create a `Napi::Object` object
- Create `Napi::PropertyDescriptor` descriptors that you need
- Use the `Napi::Object::DefineProperties` method that take a list of properties as parameters.

At moment I don't have a solution @gabrielschulhof do you have some idea about that?

**Comment by gabrielschulhof** [comment]
With https://github.com/nodejs/node-addon-api/pull/610 we should be able to do it.

**Comment by NickNaso** [comment]
Great I want work on this after your PR will be landed.

**Comment by NickNaso** [comment]
Ok https://github.com/nodejs/node-addon-api/pull/610 has been landed, now I can start working on this.
