### ISSUE TITLE
Context parameter on thread safe function callback

### ISSUE THREAD

**Issue by legendecas** [nodejs/node-addon-api#653]
Currently `Napi::ThreadSafeFunction` accepts a type implementing `void operator()(Napi::Env env, Function jsCallback, DataType* data)`. It would be hard to retrieve the initial context parameter on `Napi::ThreadSafeFunction::New` since there is only one parameter `DataType* data` or we have to wrap the data with a reference to context _again_.

**Comment by legendecas** [comment]
As a reference `napi_threadsafe_function_call_js` has a signature of

```
typedef void (*napi_threadsafe_function_call_js)(napi_env env,
                                                 napi_value js_callback,
                                                 void* context,
                                                 void* data);
```

**Comment by KevinEady** [comment]
Looking at the signature for our `CallJS` wrapper passed to `napi_create_threadsafe_function`:

https://github.com/nodejs/node-addon-api/blob/4e885069f1721dec1705c898383625dd2907f9e6/napi-inl.h#L4572-L4575

... we completely ignore the `context` data type.

The context is not wrapped, so one could use `ThreadSafeFunction::GetContext()` but it is an additional call that shouldn't be necessary.

**Comment by legendecas** [comment]
> The context is not wrapped, so one could use ThreadSafeFunction::GetContext() but it is an additional call that shouldn't be necessary.

I've considered this option. It seems on the user callback we don't have the reference to call `ThreadSafeFunction::GetContext()` if we don't wrap it in the data. So the option still relies on wrapping around data.

**Comment by gabrielschulhof** [comment]
From https://github.com/nodejs/node-addon-api/issues/594#issuecomment-581502550 it looks like we may need to substantially revamp `Napi::ThreadSafeFunction`. When we do so, we should also address this issue.

**Comment by KevinEady** [comment]
Sooo I have been working on this for some time now... After struggling with templated std::functions for hours, I really see two ways of implementing:
1. Allow the existing `[Non]BlockingCall()`s to take a three-argument callback, with the context being `void*`. 
2. Create a new function `[Non]BlockingCallEx` which _requires_ a three argument callback. I _think_ I can make the context argument templated `T *`... but since the context is stored on the underlying `napi_threadsafe_function` and not the call itself, the node-addon-api wrapper to run the callback `void(Env, Function, T*)` would perform a cast to `T*` on the context, since it's [void*](https://github.com/nodejs/node-addon-api/blob/7f56a78ff7eab77f1316696aef1de3304b70e639/napi-inl.h#L4575). 

I dunno, I am leaning towards option 1... i'm sure there are other options but there was no way I could figure out how to "combine" the two options (modify the existing callbacks to allow templated argument third `T* context`)...

Thoughts? 

cc: @gabrielschulhof @legendecas
