### ISSUE TITLE
Fundamental issues with ThreadSafeFunction

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/node-addon-api#665]
The two issues below point to some fairly core problems with the current implementation of `Napi::ThreadSafeFunction`.

https://github.com/nodejs/node-addon-api/issues/653
https://github.com/nodejs/node-addon-api/issues/594

We may well have to create a new implementation, while at the same time retaining maximum backward compatibility and as smooth a transition path as possible for those who need the functionality mentioned in the issues above.

**Comment by KevinEady** [comment]
I have started working on #653. I will put any comments on that thread.

**Comment by KevinEady** [comment]
@gabrielschulhof / @legendecas / @mhdawson :

In response to this, I think a solution that can solve both problems above, is actually to create a new templated class `ThreadSafeFunctionEx<Context>` that:
- Getting rid of the "given-per-call" callback method signatures of [`[Non]BlockingCall`]( https://github.com/nodejs/node-addon-api/blob/d43da6ac2b4bf8519afcad08b59a9223257e6979/napi-inl.h#L4457-L4470). 
  - This also addresses the concerns in https://github.com/nodejs/node-addon-api/issues/594#issuecomment-581502550 , and since this would be a _new_ class, it will not break existing code. People can migrate to this `ThreadSafeFunctionEx` class when needed, or start developing using it immediately.
  - I think this would then inherently _solve_ the above issue, because then the `[Non]BlockingCall` translates directly to a `napi_call_threadsafe_function`
- Getting rid of above makes it _much_ simpler to fix #653 which I've been struggling on for awhile
- And what about this, not sure though: Has only _one_ `New` method, thereby putting the "what parameters are optional" into the logic of underlying [napi_create_threadsafe_function](https://github.com/nodejs/node-addon-api/issues/594#issuecomment-581502550) Eg: if you do not want an `async_resource`, you would need to pass an empty `Value()`. This is for sake of keeping the code easily maintainable. (NB: need to figure out how nullptr context works, eg. maybe its `ThreadSafeFunctionEx<nullptr_t>`) 
  - Could possibly default some arguments on the `New` method signature

I was originally against the creation of a new class but I just now saw the comment I linked above talking about removing those `[Non]BlockingCall` signatures and so maybe this is the best way forward...  I should be on next weeks napi call to discuss.

Thanks, Kevin

**Comment by legendecas** [comment]
>  if you do not want an async_resource, you would need to pass an empty Value()

This reminds me that maybe we can introduce `Maybe` box into node-addon-api to provide a stronger nullable contract.

**Comment by mhdawson** [comment]
@KevinEady can we share most of the code between the existing  `ThreadSafeFunction` and `ThreadSafeFunctionEx<Context>` ? If so it sounds like a good path to explore.

**Comment by KevinEady** [comment]
> @KevinEady can we share most of the code between the existing `ThreadSafeFunction` and `ThreadSafeFunctionEx<Context>` ? If so it sounds like a good path to explore.

Hi @mhdawson , posted this to https://github.com/nodejs/node-addon-api/pull/687

**Comment by mhdawson** [comment]
@KevinEady , @gabrielschulhof should we close this as fixed by #742?
