### ISSUE TITLE
Default arguments to functions

### ISSUE THREAD

**Issue by bergkvist** [nodejs/node-addon-api#680]
Is there a clean way to expose a function with a default argument using node-addon-api?

In JavaScript, I can define a function with a default argument like this:
```js
const add = (x, y = 3) => x + y
add(0) // 3
add(7, 4) // 11
```

The first thing that comes to mind when implementing the equivalent with node-addon-api in C++ is to use a lambda expression to get the second argument:
```cpp
#include <napi.h>

Napi::Number add(Napi::CallbackInfo &args) {
  auto env = args.Env();
  double x = args[0].As<Napi::Number>().DoubleValue();

  double y = [&]() {
    if (args.Length() < 2) return double(3.0);
    return args[1].As<Napi::Number>().DoubleValue();
  }();

  return Napi::Number::New(env, x + y);
}

Napi::Object init(Napi::Env env, Napi::Object exports) {
  exports.Set("add", Napi::Function::New(env, add, "add"));
  return exports;
}

NODE_API_MODULE(NODE_GYP_MODULE_NAME, init)
```

Default arguments are supported by JavaScript functions (since something like ES6). Does this mean there is a C++-api for handling this in v8? I couldn't really find any documentation about default arguments to JavaScript-functions in the node-addon-api documentation.

**Comment by ikokostya** [comment]
> Default arguments are supported by JavaScript functions (since something like ES6). Does this mean there is a C++-api for handling this in v8?

As I known - no. `Napi` provides only [`CallbackInfo`](https://github.com/nodejs/node-addon-api/blob/master/doc/callbackinfo.md) object, which allows access to passed arguments through [index operator](https://github.com/nodejs/node-addon-api/blob/master/doc/callbackinfo.md#operator-). Therefore, to implement optional argument in C++ side you should use the following code:

```cpp
if (info.Length() > 1 && !info[1].IsUndefined()) {
  double n = info[1].As<Napi::Number>();
}
``` 

with 2 notes:

1. Check for argument count can be omitted, because access to `info[1]` [returns](https://github.com/nodejs/node-addon-api/blob/e1a827ae295d4e426ab6c77272c3f3e87e31817c/napi-inl.h#L2748-L2750) `Napi::Undefined` without overflow.
2. Check for `undefined` value is necessary if you want to repeat JavaScript behavior (you can pass `undefined` in place of optional parameter):

   ```js
   add(0, undefined) // 3
   ```

**Comment by gabrielschulhof** [comment]
As a general principle it's not a good idea to do argument juggling on the C++ side, because checking argument length or argument data type is a very expensive operation and it'll slow down the native addon. In general it's best to do argument validation on the JS side and then to accept a known number of arguments having well-established types on the native side.

**Comment by ikokostya** [comment]
> because checking argument length or argument data type is a very expensive operation and it'll slow down the native addon

Do you have any benchmarks? Getting length is constant time operation: 

```cpp
inline size_t CallbackInfo::Length() const {
  return _argc;
}
```
and checking data type is one call of `napi_typeof()` function:

```cpp
inline bool Value::IsUndefined() const {
  return Type() == napi_undefined;
}

inline napi_valuetype Value::Type() const {
  if (IsEmpty()) {
    return napi_undefined;
  }

  napi_valuetype type;
  napi_status status = napi_typeof(_env, _value, &type);
  NAPI_THROW_IF_FAILED(_env, status, napi_undefined);
  return type;
}
```

> In general it's best to do argument validation on the JS side and then to accept a known number of arguments having well-established types on the native side.

It sounds very annoying, because of need to wrap each native class on JS side if it has non-trivial parameters.

**Comment by gabrielschulhof** [comment]
@ikokostya in general the JS engine can optimize the validation code, whereas calling across library boundaries repeatedly to establish the type of something is more expensive.

[`napi_typeof()`](https://github.com/nodejs/node/blob/362e4a1aec46f386b7bc5a1b3493c690976d9105/src/js_native_api_v8.cc#L1746-L1787) actually performs many calls into the engine.

**Comment by devsnek** [comment]
By the way to match js default arguments, in the context of node-addon-api, you should use `info[i].IsUndefined()`, not argc checks. `((a = 3) => a)(undefined)` is `3`.
