### ISSUE TITLE
About BigInt usage

### ISSUE THREAD

**Issue by Catutigernos** [nodejs/node-addon-api#706]
Hi,
I am developing a module has some function get 64 bit integer as parameter, javascript side I sent as bigint, but native side I can not get the parameter with NAPI. I check lib, and BigInt is guarded in native library, and I check parameter type in native side, variable type is 9, and I cannot find the type in napi_valuetype enum. How could I get the 64 bit number? If I can't when BigInt will be published?

Thanks in advance.

**Comment by NickNaso** [comment]
Hi @Catutigernos,
if you want to use `BigInt` you need to define `NAPI_EXPERIMENTAL` macro in your code because  until N-API version 5 `BigInt` is an experimental feature. 
We are working on a new version here https://github.com/nodejs/node-addon-api/issues/689 where we support N-API version 6 that includes `BigInt` as stable API.

**Comment by Catutigernos** [comment]
Hi @NickNaso, 
Thanks for your response. I will try, but I am not sure about its reliability, because it can be unstable. Is there any estimated release date for N-API 6?

**Comment by mhdawson** [comment]
It's in 10.x and 14.x (see https://github.com/nodejs/node/blob/master/doc/api/n-api.md for the version where it was added) I think just waiting on the next SemVer minor of 12.x for it to be there.

**Comment by gabrielschulhof** [comment]
@Catutigernos N-API 6 should now be available across all LTS versions. Please re-open this issue and/or file a new one if you still have questions!
