### ISSUE TITLE
Can we use Client Stub Generated by MIDL compiler to Connect To Windows RPC Server

### ISSUE THREAD

**Issue by contradictionary** [nodejs/node-addon-api#728]
We Have a Backend Server that runs on Windows, Listens for Client using RPC
So far we've are connecting to that Server From a DLL which uses the Client Stub to Connect to and Maker different API calls with Server.

I would like to know if it is possible & feasible to use these client stubs with node-addon-api.
some examples will be helpful.

[MIDL](https://docs.microsoft.com/en-us/windows/win32/midl/files-generated-for-an-rpc-interface)

Appreciate any response.
Thanks

**Comment by gabrielschulhof** [comment]
@contradictionary if you wish to use the DLL from Node.js, you have to write Node.js bindings for the native functions it provides. There are two ways of doing that:

0. If you are "in control" of the DLL, meaning you have the source code and are able to build it yourself, you can add bindings to it and it will become a Node.js addon.

0. If you do not have the source code for it, you can still link to it from a newly created Node.js addon by  including the corresponding `.lib` in the binding.gyp file responsible for building the Node.js addon.

**Comment by contradictionary** [comment]
@gabrielschulhof, thanks for the details.

Can you Give me some Example links for point 0.

**Comment by gabrielschulhof** [comment]
@contradictionary one approach to adding bindings would be to add a package.json and binding.gyp file to the DLLs repository and then to call the DLLs build system from binding.gyp as a dependency of building the bindings. So, when you do npm install from the DLL repo's root directory, it would build the DLL, though perhaps it would link it into a static library rather than a dynamic one, and then it would build additional files containing the bindings and finally link everything into a Node.js addon.

**Comment by gabrielschulhof** [comment]
@contradictionary a somewhat outdated example can be found at https://github.com/intel/iotivity-node/blob/master/binding.gyp#L200 where the files listed in `sources` are the bindings and the dependency `csdk` is the C library which is being built using scons.
