### ISSUE TITLE
How to call a Napi::Function callback from a lambda function?

### ISSUE THREAD

**Issue by erikjalevik** [nodejs/node-addon-api#772]
I'm having some trouble figuring out how to keep hold of a callback function passed in from JS, and then call it from a lambda function invoked asynchronously. The `Napi::AsyncWorker` isn't suitable here as I'm calling a library (the `doWork` function) that already handles the threading and accepts a callback parameter when invoked. It invokes the callback on the main thread.

Here's what I tried:

```
void exportedFunction(const Napi::CallbackInfo& info)
{
  auto env = info.Env();
  Napi::FunctionReference callback = Napi::Persistent(info[0].As<Napi::Function>());
  doWork([=] () // compiler error here because FunctionReference cannot be captured
  {
    Napi::HandleScope scope(env);
    callback.Call({});
  });
}
```

This does not compile because the `FunctionReference` disallows being copied by value into the lambda.

I also tried with a `std::shared_ptr`:

```
void exportedFunction(const Napi::CallbackInfo& info)
{
  auto env = info.Env();
  std::shared_ptr<Napi::Function> pCallback(new Napi::Function(env, info[0].As<Napi::Function>()));
  doWork([=] ()
  {
    Napi::HandleScope scope(env);
    try
    {
      pCallback->Call({});
    }
    catch (const std::exception& e)
    {
      // e.what() contains "Invalid argument"
    }
  });
}
```

Here `Call` throws with an error of "Invalid argument" (incidentally the same error as if capturing a naked `Napi::Function` and trying to call it from the lambda after its handle scope is gone).

Invoking the callback before calling `doWork` works fine.

What is the correct way of doing this with node-addon-api?

**Comment by KevinEady** [comment]
Hi @erikjalevik ,

Check out [`ThreadSafeFunction`](https://github.com/nodejs/node-addon-api/blob/master/doc/threadsafe_function.md). You'll create an instance of the `Napi::ThreadSafeFunction` on the main thread (which accepts a parameter of a `Napi::Function`). You can then call `ThreadSafeFunction::[Non]BlockingCall()` on any thread to call the registered `Napi::Function`.

Does this help?

Thanks, Kevin

**Comment by KevinEady** [comment]
Aaaack @erikjalevik sorry to (possibly) steer you down the wrong path, I just saw this part of your comment:

> It invokes the callback on the main thread.

So, if you have a `FunctionReference` ... you can access the `reference.Value()` which will give you a `Napi::Function` which you can call via `func.Call()` if you are guaranteed to be on the main thread. Does this make sense / help?

Thanks, Kevin

**Comment by erikjalevik** [comment]
Thanks a lot for the quick reply, @KevinEady, looks promising!

However, as I sat down to try this out, I ended up in a bit of a catch-22. The whole reason for adopting N-API is that we're trying to upgrade an Electron app with some custom native add-ons from Electron version 2.0.8, which means Node 8.9.3, and 8.9.3 does not yet have the `napi_create_threadsafe_function` API (added in 10.6.0).

As I'm writing this, your second reply popped up, and indeed, the callback is getting invoked on the main thread. (I just double-checked this in the Xcode debugger).

However, even if using `Value()`, the trouble is I'm not able to get the `FunctionReference` captured by the lambda, since it lacks a copy constructor.

In our previous Nan/V8 implementation, we had code like the following, which worked just fine:

```
void exportedFunction(const v8::FunctionCallbackInfo<v8::Value>& Args){
   v8::Isolate* pIsolate = Args.GetIsolate();
 
   std::shared_ptr<Nan::Callback> pCallback(new Nan::Callback());
   if (Args.Length() == 1 && Args[0]->IsFunction())
   {
     pCallback->Reset(Args[0].As<v8::Function>());
   }
   else
   {
     // throw
   }
 
   doWork([pIsolate, pCallback] ()
   {
     pCallback->Call(0, 0);
   });
}
```

So I was hoping there would be some direct N-API equivalent, and `FunctionReference` does seem like it would do the job if it only allowed capturing by the lambda...

Aah, wait. 💡 Maybe you mean calling `Value()` outside of the lambda and then letting the lambda capture only the `Napi::Function`! Let me go and try that.

**Comment by erikjalevik** [comment]
Strangely enough, this doesn't work either:

```
static Napi::FunctionReference callbackRef;
void exportedFunction(const Napi::CallbackInfo& info)
{
  auto env = info.Env();
  callbackRef = Napi::Persistent(info[0].As<Napi::Function>());
  Napi::Function callback = callbackRef.Value();
  doWork([env, callback] ()
  {
    Napi::HandleScope scope(env);
    try
    {
      callback.Call({});
    }
    catch (const std::exception& e)
    {
      // e.what() contains "Invalid argument"
    }
  });
}
```

**Comment by KevinEady** [comment]
Hey @erikjalevik ,

Check out https://github.com/KevinEady/node-addon-examples/blob/node-addon-api-issue-772/1_hello_world/node-addon-api/hello.cc 

If you clone the branch and repo, you can run the example by executing in the example's directory `npm i && node .` .. You should see:

```
➜  node-addon-api git:(node-addon-api-issue-772) ✗ npm i && node .

> hello_world@0.0.0 install /Users/kevineady/Documents/Projects/node-addon-examples/1_hello_world/node-addon-api
> node-gyp rebuild

  CXX(target) Release/obj.target/hello/hello.o
  SOLINK_MODULE(target) Release/hello.node
audited 2 packages in 3.708s
found 0 vulnerabilities

bar cpp-arg0 cpp-arg1
AddonInstance {}
```

Does this example help?

Note that you must be 100% sure that your `doWork()` is actually being executed on the main thread (like mine is)

**Comment by erikjalevik** [comment]
Hi @KevinEady, thanks a lot for taking the time to provide a fully working example!

I see that you are getting around the problem of the non-copyable `FunctionReference` by adding a new container class for the purpose of keeping the callback reference alive, and then exporting this whole class to JS. Then in the exported function, you capture `this` into the lambda instead, which is by reference, thus avoiding having to copy the `FunctionReference`, and that's why it works.

This is a neat solution, even though, if I understand it correctly, it shifts the responsibility for lifetime management of the function reference (via `AddonInstance`) over to the JS side (what if the whole instance gets garbage collected before the callback is invoked?). 

It would also require quite a bit of refactoring of our existing codebase to mould it into this pattern, instead of the straight-forward Nan/V8 implementation, with locally managed lifetimes, that we have now. This module exports some 20 functions, so we'd need to keep the function references to all of these callbacks as separate instance members for the new class. Hmm... Will need to have a little think about this to see if I could massage it into a workable shape for us.

(Btw, I see from your profile you're in Berlin! Me too. :)

**Comment by erikjalevik** [comment]
I found a simpler solution by dropping down to the C API, which allows us to use the existing code structure:

```
void exportedFunction(const Napi::CallbackInfo& info)
{
  auto env = info.Env();
  napi_ref ref;
  napi_create_reference(env, info[0].As<Napi::Function>(), 1, &ref);
  doWork([env, ref] ()
  {
    Napi::HandleScope scope(env);
    Napi::FunctionReference callback(env, ref);
    callback.Call({});
  });
}
```

**Comment by KevinEady** [comment]
Hi @erikjalevik ,

Yes, attaching the method to the `AddonInstance` class I made indeed moves the lifetime management to JS. This is an approach in order to make addons context-sensitive: having a `static FunctionReference callbackRef` (like in your first example) is _not_ context-sensitive, in the sense that if your addon is loaded multiple times in different contexts (using the `vm` module, worker threads, ...), this static data will interfere with each other.

The difference between using `Napi::Reference` and a native `napi_reference`:
1. `Reference::New` has proper checks and fails for napi calls. `napi_create_reference` returns a status code saying whether it failed. See [the implementation](https://github.com/nodejs/node-addon-api/blob/5af645f64900044971787b092567998be784dcb5/napi-inl.h#L2329).
2. The `~Reference` destructor will [release the reference](https://github.com/nodejs/node-addon-api/blob/master/napi-inl.h#L2355).

Using `static FunctionReference` like you were, also leaves the destruction of the object to the static runtime de-initialization, which I'm fairly certain happens _after_ the node instance has already shut down. [@gabrielschulhof  / @mhdawson please correct me if i'm wrong] I assume your native C N-API example "works" because you are not properly deleting the reference, and `ref` points to invalid data that has already been freed (but nothing _accesses_ it, so it "works"). Are you calling `napi_delete_reference` anywhere in your code? 

Node-addon-api is just a wrapper around N-API so you should be able to use this as well...
1. Your `FunctionReference` needs to be stored somewhere that you know that its destructor will happen _before_ Node's environment is cleaned up. In _my_ example, I gave it to JS (and in my example's specific use-case the object is not GC'd before work is done, so it's fine in _my_ example)
2. You should delete the reference in whatever your library's de-initialization method is (ie. hopefullly your library has some way to say "i am done" perhaps via callback). ... this is where you would do your delete reference. My example deletes the reference due to the GC deleting the data _prior_ to 100% finalization of the Node environment (when you use a `static FunctionReference`, this is not the case)

NOTE: There is also [`Reference<T>::SuppressDestruct()`](https://github.com/nodejs/node-addon-api/blob/master/doc/reference.md#suppressdestruct) which will prevent the destructor from deleting the reference as well. This is the equivalent of what you're doing in your _new_ example: creating the reference and not deleting it. Perhaps this will solve your issue if you want to go with node-addon-api in your most recent example.

**Comment by erikjalevik** [comment]
Hi again, and thanks for clarifying.

The file static `FunctionReference` was just a quick experiment, not intended for production code, so please disregard that.

Correct me if I'm wrong, but here's my understanding of why my C API solution works:

1. The `napi_create_reference` call creates a reference to the function with a refcount of 1, so it will survive past the end of the native method call. (I have added the required error handling in the production code, the snippet posted here was just for illustration.)
2. This `napi_ref` gets captured by value into the lambda.
3. When the lambda is invoked, the `ref` is still valid due to its refcount still being 1.
4. By using the constructor of `FunctionReference` which takes a `napi_ref` (`FunctionReference(napi_env env, napi_ref ref)`), I am handing over ownership of the ref to it.
5. At the end of the lambda function scope, `FunctionReference`'s destructor is called, since it's on the stack. The destructor then takes care of deleting the ref. I can see from `napi-inl.h` that it invokes `napi_delete_reference`.

What worries me is your statement that "I assume your native C N-API example "works" because you are not properly deleting the reference, and ref points to invalid data that has already been freed". Why would the ref be invalid in this case? I assumed it would remain valid due to its refcount being 1?

**Comment by KevinEady** [comment]
Hi @erikjalevik ,

Perhaps I misspoke. Your logic is 100% correct, especially regarding the ref lifecycle stuff. By "invalid data", I mean: if you have your `static napi_ref` data somewhere, and you do not explicitly call `napi_delete_reference()`, it will _eventually_ be deleted by Node when Node shuts down (which makes sense: you cant use JS when theres no more node), so everything is correct in that sense. The "invalid" nature is that your `napi_ref ref` will hold a value that points to some reference that is no longer relevant (because node is no longer initialized) and the memory has been freed by node as node has shut down. This is obviously okay, but you just need to be aware that you can't rely on `ref != nullptr` checks for "is this reference valid / active".

Does this make sense?

Thanks, Kevin

PS: 👋  from Berlin 🇩🇪 ! 😄
