### ISSUE TITLE
napi_throw_error function syntax in Node v8.2.1 and below is different from N-API V1 docs

### ISSUE THREAD

**Issue by kanikashah90** [nodejs/node-addon-api#778]
In Node v8.2.1 N-API [docs](https://nodejs.org/dist/v8.2.1/docs/api/n-api.html#n_api_napi_throw_error) syntax for `napi_throw_error` is:
`NODE_EXTERN napi_status napi_throw_error(napi_env env, const char* msg);`

Whereas in the latest Node v14 [docs](https://nodejs.org/dist/latest-v14.x/docs/api/n-api.html#n_api_napi_throw_error) syntax is:
`NAPI_EXTERN napi_status napi_throw_error(napi_env env,
                                         const char* code,
                                         const char* msg);`
Node v14 docs mention that this method was introduced in **N-API version 1** in **Node v8.0.0**.

`code` argument is missing in the Node v8.2.1.

When I compile my native add-on compiled using NAPI in Node v8.17.0 it fails to work in Node v8.2.1. And due to syntax differences, the module fails to compile on 8.2.1.

**Comment by NickNaso** [comment]
Hi @kanikashah90,
this issue is correlated to this other one **https://github.com/nodejs/node-addon-api/issues/760**, now we are updating the documentation in the core through this PR https://github.com/nodejs/node/pull/34344.

The first version that matches version 1 is 8.6.0. N-API was introduced in version v.8.0.0 as experimental and version 1 continued to evolve until v8.7.0 and therefore the shape of the API in earlier versions is not truly version 1 (in hindsight we should have called it version 0). We recommend version 3 or later.

Hope that this help you.

**Comment by gabrielschulhof** [comment]
The documentation fix to address this issue has landed in core at https://github.com/nodejs/node/pull/34344.
