### ISSUE TITLE
How to return objects in class methods?

### ISSUE THREAD

**Issue by kaysonwu** [nodejs/node-addon-api#813]
I have the following 2 classes, now I need to encapsulate Hero into a node module

```cc
class Pet {
    public:
        Pet(const char* name);
        void Say();
    protected:
        const char* Name;
}

class Hero {
    public:
        Hero(const char* name);
        Pet GetPet();
    protected:
         const char* Name;
        Pet Pet;
}
```

I refer to the [Wrapping C++ Object](https://github.com/nodejs/node-addon-examples/tree/master/6_object_wrap/node-addon-api) example, but I cannot complete the encapsulation of the `GetPet` method in the `Hero` class.

**How can I implement `GetPet` to return the `Pet` object and customize its public methods?**

**Comment by kaysonwu** [comment]
I made an example [9_object_wrap](https://github.com/kaysonwu/node-addon-examples/tree/master/9_object_wrap/node-addon-api),  I found that the Pet object was free early, how can I solve it?

**Comment by mhdawson** [comment]
@kaysonwu I think the problem is this line `Pet(Pet::New(info.Env(), info[1].As<Napi::String>()))`

This results in a  a Pet JavaScript object that will only live as long as the method Hero::Hero is running since the object is not returned by the method and no JavaScript object references the object in the JavaScript heap. You do have a reference at the C++ level but that will not keep the object alive.  

I think you need to use an ObjectReference https://github.com/nodejs/node-addon-api/blob/master/doc/object_reference.md. When hero is then destructed that should then result in the reference count to Pet being decreased and it being ready to be collected by the garbage collector.

**Comment by gabrielschulhof** [comment]
@kaysonwu hopefully @mhdawson's suggestion solved the problem you were experiencing. Please re-open the issue if you believe there is any functionality in node-addon-api that needs to change to better support your use case!
