### ISSUE TITLE
save javaScript function to c++

### ISSUE THREAD

**Issue by x93008** [nodejs/node-addon-api#833]
Can I save the javascript anonymous function in c++ and call it infinitely many times when c++ needs it? and the function modifies the variables captured by javascript when defining the function.

**Comment by x93008** [comment]
/*******************
* this is my cpp file */

#include <memory>
#include <napi.h>

static Napi::Function cb_;
static std::shared_ptr<Napi::Env> env_;

void SaveCallback(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  Napi::Function cb = info[0].As<Napi::Function>();
    cb_ = cb;
    env_ = std::make_shared<Napi::Env>(env);
}

void Run(const Napi::CallbackInfo& info) {
   cb_.Call({Napi::String::New(*env_, "hello world callback")});
}

static Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set(Napi::String::New(env, "saveCallBack"),
              Napi::Function::New(env, SaveCallBack));
  exports.Set(Napi::String::New(env, "run"),
              Napi::Function::New(env, Run));
  return exports;
}

NODE_API_MODULE(addon, Init)




/*****************
* this is my js file
***********************/
var addon = require('./build/lib/build-node-addon-api-with-cmake');

addon.saveCallback(function(msg){
  console.log(msg);
});

setTimeout(() => {
    console.log('run');
    addon.run();
}, 3000);

**Comment by x93008** [comment]
// this console log
run

~/cpp_to_nodejs/hello.js:12
    addon.run();
          ^

Error: Invalid argument
    at Timeout._onTimeout (~/cpp_to_nodejs/hello.js:12:11)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)

**Comment by KevinEady** [comment]
Hi @x93008 . You are having a fundamental issue regarding the concepts of lifetime management for Node objects.

```cpp
void SaveCallback(const Napi::CallbackInfo& info) {
    Napi::Env env = info.Env();
    Napi::Function cb = info[0].AsNapi::Function();
    cb_ = cb;
    env_ = std::make_sharedNapi::Env(env);
}
```

1. JavaScript is a garbage-collected language, and in order to do so, it uses reference counts in order to know when something is available for deletion. This means you can't "store" any _values_ per se, but you can store a _reference_ to a value. For your use-case, you will need to change your `cb_` to a [FunctionReference](https://github.com/nodejs/node-addon-api/blob/master/doc/function_reference.md) 

2. You should _never_ store an `Env`. In all the cases whenever you need to access an `Env`, it should be provided to you as an argument within the scope. You should remove your `env_`, and when you make your call to `cb_`, you will create the string parameter using `Napi::String::New(info.Env(), "hello world callback")`. If you are storing _references_, you can get the reference's environment using `ref.Env()` as well; you can _never_ just store the value as a raw `Env`.

Let us know if this helps.

**Comment by x93008** [comment]
Thank you, that's very helpful to me.
