### ISSUE TITLE
How to create a new Buffer from chars?

### ISSUE THREAD

**Issue by searene** [nodejs/node-addon-api#845]
I've been fiddling with `Napi::Buffer` for a long time, but haven't figured out how to create a `Buffer` correctly. The resulting `Buffer`'s content is just incorrect. This is my cpp code:

```cpp
#include <napi.h>

Napi::Value GetBuffer(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  std::vector<char> v{0x10, 0x11, 0x12};
  return Napi::Buffer<char>::New(env, v.data(), v.size());
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
  exports.Set(Napi::String::New(env, "getBuffer"), Napi::Function::New(env, GetBuffer));
  return exports;
}

NODE_API_MODULE(addon, Init);
```

This is my js code
```js
const addon = require('./build/Release/addon');
const buffer = addon.getBuffer();
console.log(buffer.toString("hex")); // The output is different every time, instead of being 101112
```

The resulting buffer's contents are always different, why? Am I doing something wrong?

**Comment by KevinEady** [comment]
I would gander it's because you are creating a vector on the stack that gets deallocated once the `GetBuffer()` call ends. The native data that the `Napi::Buffer` needs to be available for the lifetime of the `Buffer` object itself. See the documentation for the different [`New` overloads](https://github.com/nodejs/node-addon-api/blob/master/doc/buffer.md#new-1): they briefly touch on data ownership and how you need to manage your data. 

Let us know if you need additional guidance.

Thanks, Kevin

**Comment by searene** [comment]
@KevinEady Thanks for the quick reply, I got it. For anyone who encounter the problem in the future, I just used the [Copy](https://github.com/nodejs/node-addon-api/blob/master/doc/buffer.md#copy) method to solve the problem, here is a sample code:

```cpp
Napi::Value GetBuffer(const Napi::CallbackInfo& info) {
  Napi::Env env = info.Env();
  std::vector<char> v{0x10, 0x11, 0x12};
  return Napi::Buffer<char>::Copy(env, v.data(), v.size());
}
```
