### ISSUE TITLE
MSVC needs -D _HAS_EXCEPTIONS=1 for exceptions to work properly

### ISSUE THREAD

**Issue by mika-fischer** [nodejs/node-addon-api#85]
This should be added to the instructions in the README.

```
'conditions': [
    ['OS=="win"', { 'defines': [ '_HAS_EXCEPTIONS=1' ] }]
]
```

**Comment by jasongin** [comment]
Why? Can you explain what problem you're seeing without that define? There are [tests ](https://github.com/nodejs/node-addon-api/blob/master/test/error.cc) of the exception behavior that seem to work fine without it.

As far as I know, `_HAS_EXCEPTIONS=1` is the default for MSVC. Some projects may override it to 0. But in that case, they'd probably want `'NAPI_DISABLE_CPP_EXCEPTIONS` instead.

**Comment by mika-fischer** [comment]
Thing work to some degree without it but there are subtle memory errors. I don't understand exactly what this flag causes but the effect is that objects are freed to early when handling an exception.

For instance try this with `_HAS_EXCEPTIONS=0` and `_HAS_EXCEPTIONS=1`:
```
try
{
    throw std::runtime_error(std::string("abc"));
}
catch (std::exception& e)
{
    std::cout << "'" << e.what() << "'" << std::endl;
}
```

For me with MSVC 2015 this reliably prints `''` with `_HAS_EXCEPTIONS=0`. But I've also encountered garbage memory in other cases. Needless to say this was a huge pain to debug and thus I think it should be much more prominently documented.

The define comes from nodejs itself: https://github.com/nodejs/node/blob/master/common.gypi#L273

See also https://github.com/nodejs/node-gyp/issues/939 which led me to the solution.

**Comment by jasongin** [comment]
Interesting. Thanks for the details. And I didn't realize node `common.gypi` set `_HAS_EXCEPTIONS=0`. I agree then it should be added to the README.

**Comment by DBJDBJ** [comment]
### Abstract
[The author measures size costs of error handling approaches. Exceptions are big, `std::abort` and integer error codes are small.](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1640r1.html)

**Comment by NickNaso** [comment]
Hi @DBJDBJ,
thanks for reporting the paper about performance on error handling. `node-addon-api` allow you to enable or disable the exception mechanism. 
It is documented on the following sections:
- **[Setup](https://github.com/nodejs/node-addon-api/blob/master/doc/setup.md)**
- **[Error handling](https://github.com/nodejs/node-addon-api/blob/master/doc/error_handling.md)**

If you enable the exceptions you will have a little overhead and it could be acceptable or not. 

I'm closing this because now the error handling for `node-addon-api` is documented like how it's pisbbile to enable or disable the exception mechanism.

**Comment by DBJDBJ** [comment]
> If you enable the exceptions you will have a little overhead and it could be acceptable or not

Many thanks for the quick comment. I appreciate the answer. 

I might be so bold to think we (the native node.js community and customers) do require a bit more precise size and performance results than "you will have a little overhead..." ... has anyone (tasked by node team) measured the impact of exceptions recently? on the 3 key platforms with the 3 key compilers. I am trying to stay high level here. :)

**Comment by zbjornson** [comment]
@NickNaso This issue was closed but the documentation was never updated. Here's a simple example that doesn't catch correctly without `"defines": ["_HAS_EXCEPTIONS=1"]`:

```c++
#include<new>

Napi::Value test(const Napi::CallbackInfo& info) {
   Napi::Env env = info.Env();
   try {
      uint64_t* ptr = new uint64_t[0xFFFFFFFFFFFFUL];
      delete[] ptr;
   } catch(const std::bad_alloc& ba) {
      throw Napi::Error::New(env, ba.what());
   } catch(...) {
      throw Napi::Error::New(env, "This shouldn't be the one that catches");
   }
   return Napi::Number::New(env, 0);
}

Napi::Object Init(Napi::Env env, Napi::Object exports) {
	exports.Set(Napi::String::New(env, "test"), Napi::Function::New(env, test));
	return exports;
}

NODE_API_MODULE(xxx, Init)
```

**Comment by NickNaso** [comment]
Hi @zbjornson,
sorry I made a mistake on closing the issue. Now i'm preparing a PR to solve the problem. Thanks for your feedback.

**Comment by DBJDBJ** [comment]
Ok here is what precisely happens if one compiles with `-D_HAS_EXCEPTIONS=0`, on Windows.

`_CPPUNWIND`  becomes 0. Keywords `try`,`throw`, `catch` cease to exist and WIN32 SEH aka "Structured Exceptions Handling" is being used everywhere like for example in MS STL.

This is primarily the side effect of using cl.exe (MSVC compiler) with the `/kernel` switch, to created kernel-mode DLL's.

May thanks  ...
