### ISSUE TITLE
FATAL ERROR: Error::Error napi_create_reference

### ISSUE THREAD

**Issue by seishun** [nodejs/node-addon-api#865]
Steps to reproduce:

1. Add `throw "error";` after this line: https://github.com/nodejs/node-addon-examples/blob/3fda42d34dc8dacc34ed699693654e4a88e070a6/3_callbacks/napi/addon.js#L4
2. Build and run the example.

Expected: a JS error or a crash with a C++ exception.

Actual:

```
hello world
FATAL ERROR: Error::Error napi_create_reference
 1: 0x10137b045 node::Abort() (.cold.1) [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
 2: 0x1000be039 node::Abort() [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
 3: 0x1000be19f node::OnFatalError(char const*, char const*) [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
 4: 0x1000be049 node::FatalError(char const*, char const*) [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
 5: 0x10009340a napi_fatal_error [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
 6: 0x104e010aa Napi::Error::Fatal(char const*, char const*) [/Users/nvavilovs/node-addon-examples/3_callbacks/node-addon-api/build/Release/addon.node]
 7: 0x104e0100e Napi::Error::New(napi_env__*) [/Users/nvavilovs/node-addon-examples/3_callbacks/node-addon-api/build/Release/addon.node]
 8: 0x104e0098a RunCallback(Napi::CallbackInfo const&) [/Users/nvavilovs/node-addon-examples/3_callbacks/node-addon-api/build/Release/addon.node]
 9: 0x104e013bf napi_value__* Napi::details::WrapCallback<Napi::details::CallbackData<void (*)(Napi::CallbackInfo const&), void>::Wrapper(napi_env__*, napi_callback_info__*)::'lambda'()>(void (*)(Napi::CallbackInfo const&)) [/Users/nvavilovs/node-addon-examples/3_callbacks/node-addon-api/build/Release/addon.node]
10: 0x104e0135d Napi::details::CallbackData<void (*)(Napi::CallbackInfo const&), void>::Wrapper(napi_env__*, napi_callback_info__*) [/Users/nvavilovs/node-addon-examples/3_callbacks/node-addon-api/build/Release/addon.node]
11: 0x10008365a v8impl::(anonymous namespace)::FunctionCallbackWrapper::Invoke(v8::FunctionCallbackInfo<v8::Value> const&) [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
12: 0x1002a3dc8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
13: 0x1002a335c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
14: 0x1002a2a87 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
15: 0x100ac4979 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
16: 0x100a5daa2 Builtins_InterpreterEntryTrampoline [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
17: 0x100a5daa2 Builtins_InterpreterEntryTrampoline [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
18: 0x100a5daa2 Builtins_InterpreterEntryTrampoline [/Users/nvavilovs/.nvm/versions/node/v15.5.0/bin/node]
```

Enabling exceptions doesn't change the outcome.

**Comment by KevinEady** [comment]
Hi @seishun ,

The JavaScript exception must be handled in the native addon. After calling `napi_call_function`, the return value will be `napi_pending_exception` instead of `napi_ok`. In this scenario, you must call [`napi_get_and_clear_last_exception`](https://nodejs.org/api/n-api.html#n_api_napi_get_and_clear_last_exception) to tell the engine that execution can continue. The error thrown will be received in the `napi_value result`. If you are throwing a proper `Error` object, you can access the `message` property to get the error message (like you would in JavaScript).

Let us know if this helps.

Thanks, Kevin

**Comment by mhdawson** [comment]
To follow on to what @KevinEady.  It's likely the assert in this line https://github.com/nodejs/node-addon-examples/blob/3fda42d34dc8dacc34ed699693654e4a88e070a6/3_callbacks/napi/addon.cc#L24 which results in the FATAL_ERROR you saw not the one that you tried to throw.  The call to napi_create_reference here: https://github.com/nodejs/node-addon-api/blob/1bdc7584cdea3c5761385c7c08a06e12d9852972/napi-inl.h#L2313 likely fails because there is already an exception pending (the one you added).

**Comment by seishun** [comment]
@KevinEady Adding `env.GetAndClearPendingException();` after this line doesn't change the outcome: https://github.com/nodejs/node-addon-examples/blob/3fda42d34dc8dacc34ed699693654e4a88e070a6/3_callbacks/node-addon-api/addon.cc#L6 Does it for you?

**Comment by gabrielschulhof** [comment]
The problem is that in your example you throw a string, whereas `Napi::Error` expects the error to be an object. I don't quite understand why `Napi::Error` has to be descended from `Napi::ObjectReference`, but it's causing a problem unique to node-addon-api.

**Comment by gabrielschulhof** [comment]
IOW, the constructor for `Napi::Error` accepts a `napi_value` that must be an object because the constructor attempts to create a `napi_ref` to it, and `napi_ref`s to non-objects cannot be created.

@nodejs/n-api an interesting aside: we chose to disallow references to non-objects such as numbers or strings or boolean values. Was it because ChakraCore did not support such references? IINM V8 supports such references and so does JerryScript. Perhaps its time to re-evaluate this limitation.

**Comment by gabrielschulhof** [comment]
We added the limitation in https://github.com/nodejs/node/commit/cb9490577412046f050d786d7a0c842980149a20 with the justification that such an operation is not supported by all engines. It may be time to re-evaluate this.

**Comment by gabrielschulhof** [comment]
The reasoning behind why a `Napi::Error` must be an instance of `Napi::ObjectReference` is here: https://github.com/nodejs/node-api/issues/31

**Comment by mhdawson** [comment]
Closing this issue as there has not been a follow up since Gabriel's responses. Please let us know if that was not the right thing to do.
