### ISSUE TITLE
How to pass a callback to an ObjectWrapper to be executed async by an already existing cpp library?

### ISSUE THREAD

**Issue by ineeve** [nodejs/node-addon-api#918]
Hi, I'm developing a Node wrapper for an existing private c++ library (let's call it X) that provides a Facade that allows me to register callbacks to listen for Entity updates.

My approach was to create a Facade Wrapper using the ObjectWrapper.
In the FacadeWrapper I want to make available a `OnEntityUpdate` method to register a callback in the underlying X library.
Once the callback is registered in the X library, it will be fired multiple times asynchronously.  

My current code looks as follows:
```cpp
class FacadeWrapper : public Napi::ObjectWrap<FacadeWrapper>
{
public:
    // Omitting initialization here as it's not important ...
    static Napi::Object Init(Napi::Env env, Napi::Object exports);
    FacadeWrapper(const Napi::CallbackInfo &info) : Napi::ObjectWrap<FacadeWrapper>(info);

private:
    Napi::FunctionReference constructor;
    X::Facade *actualClass_;
    Napi::FunctionReference jsCb;

    // This method is exported so that it can be called from JS.
    void OnEntityUpdate(const Napi::CallbackInfo &info)
    {
        Napi::Env env = info.Env();
        Napi::HandleScope scope(env);

        jsCb = Napi::Persistent(info[0].As<Napi::Function>());
        // The method onEntityUpdate belongs to the X library and it accepts a C++ callback function and a void*;
        this->actualClass_->onEntityUpdate(&emitNodeUpdateInJS, this);
    }

    static void emitEntityUpdateInJS(X::EntityUpdateEvent *event, void *this_pointer)
    {
        FacadeWrapper *self = static_cast<FacadeWrapper *>(this_pointer);
        Napi::Env env = self->jsCb.Env();
        // I would convert the event object into a JS/Napi Object here to pass it on the Call()
        self->jsCb.Call({});
    }
```

However, this doesn't work as it throws one of the following errors when executing the callback:
```
Fatal error in v8::HandleScope::CreateHandle()
Cannot create a handle without a HandleScope
------------------------------
Fatal error in HandleScope::HandleScope
Entering the V8 API without proper locking in place
```

I've spent the last 6 to 7 hours looking and experimenting with other Napi::Objects such as AsyncWorker, ThreadSafe functions, and Promises, but couldn't figure out how to apply any of them to my use case.

Any help would be kindly appreciated.

Note: The Entity Update events are generated by a thread in the X library.

**Comment by KevinEady** [comment]
Hi @ineeve,

If your library is sending events on different thread (which, I assume it is, considering it's events), you will need to use [thread-safe functions](https://github.com/nodejs/node-addon-api/blob/main/doc/threadsafe.md). Let us know if this helps.

**Comment by ineeve** [comment]
Hi @KevinEady,

Thanks for the quick reply! I was able to make it work using your suggestion.
I'm posting here my solution in case others find it useful, based on [Typed Threadsafe Function](https://github.com/nodejs/node-addon-api/blob/main/doc/typed_threadsafe_function.md#example)

```cpp
using Context = Napi::Reference<Napi::Value>;
using DataType = X::Event;
void CallJs(Napi::Env env, Napi::Function callback, Context *context, DataType *data);
using TSFN = Napi::TypedThreadSafeFunction<Context, DataType, CallJs>;
using FinalizerDataType = void;

class FacadeWrapper : public Napi::ObjectWrap<FacadeWrapper>
{
public:
    // Omitting initialization here as it's not important ...
    static Napi::Object Init(Napi::Env env, Napi::Object exports);
    FacadeWrapper(const Napi::CallbackInfo &info) : Napi::ObjectWrap<FacadeWrapper>(info);

private:
    Napi::FunctionReference constructor;
    X::Facade *actualClass_;
    TSFN tsfn;

    // This method is exported so that it can be called from JS.
    void OnEntityUpdate(const Napi::CallbackInfo &info)
    {
       Napi::Env env = info.Env();
        Napi::HandleScope scope(env);

        Context *context = new Napi::Reference<Napi::Value>(Napi::Persistent(info.This()));
        tsfn = TSFN::New(
            env,
            info[0].As<Napi::Function>(), // JavaScript function called asynchronously
            "Resource Name",              // Name
            0,                            // Unlimited queue
            1,                            // Only one thread will use this initially
            context,
            [](Napi::Env, FinalizerDataType *,
               Context *ctx) { // Finalizer used to clean threads up
                delete ctx;
            });

        // The method onEntityUpdate belongs to the X library and it accepts a C++ callback function and a void*;
        this->actualClass_->onEntityUpdate(&emitNodeUpdateInJS, this);
    }

    // These methods are part of a Napi::ObjectWrap<FacadeWrapper>
    static void emitNodeUpdateInJS(X::Event *event, void *this_pointer)
    {
        FacadeWrapper *self = static_cast<FacadeWrapper *>(this_pointer);
        TSFN tsfn = self->tsfn;
        tsfn.Acquire();
        tsfn.NonBlockingCall(event);
        tsfn.Release();
    }
}; // Closes FacadeWrapper class

// Transform native data into JS data, passing it to the provided
// `callback` -- the TSFN's JavaScript function.
void CallJs(Napi::Env env, Napi::Function callback, Context *context,
            DataType *data)
{
    if (env != nullptr)
    {
        if (callback != nullptr)
        {
            Napi::Object result = data->getNode();
            callback.Call(context->Value(), {result});
        }
    }
    if (data != nullptr)
    {
        // We're finished with the data.
        delete data;
    }
}
```

I'm still unsure about the use of the `Acquire`, `Blocking` vs `Nonblocking`, and `Release` methods, but it is working right now.

**Comment by KevinEady** [comment]
Hi @ineeve ,

So the TSFN has an internal counter that starts at the `initial_thread_count` and is increased every time you call `Acquire()` and decreased with `Release()`. Once this counter reaches `0`, the TSFN finalizer is ran, and then the TSFN is no longer usable. This enables you to create a new native thread after the TSFN has been created, and tell Node that this new thread is using the TSFN as well: by [1] calling `Aquire()`, [2] the thread creation, and [3] a `Release()` call at end of thread.

I do not think you need to `Acquire()` and `Release()` inside your `emitNodeUpdateInJS` because you do not need to modify the TSFN's internal counter, ie. there are no new threads being created. However, this begs the question: if you start the TSFN with `1` thread and no additional `Acquire()`s, you should have one `Release()` -- when your native thread finishes. Where is that? If you do not `Release()`, the Node process will remain executing -- because it thinks there is a thread using it. [NB: You can use `Unref()` to bypass this behavior, telling Node to close if there are no other events on the loop, even if the TSFN's counter has not reached 0]

Regarding `Blocking` vs `Nonblocking`: In addition to the TSFN internal counter described above, the way the TSFN allows its threadsafe APIs is via a message-queue: When you call `[Non]BlockingCall()`, your thread is adding to this queue a _request to execute_ the TSFN. There are differences in behavior depending on what you pass for `max_queue_size` when constructing the TSFN, where `0` means unlimited:
- For a limited-size queue that is full:
  - A `BlockingCall` will _block your thread_ until there is space in the queue to add. 
  - A `NonBlockingCall` will return `napi_queue_full` to tell you the queue was full, allowing you to handle this condition manually.
- For an unlimited-size queue, `BlockingCall` will never block, and `NonBlockingCall` will never return `napi_queue_full`.

Hope this provides some clarity. Let us know if you have any additional questions.

Thanks, Kevin

**Comment by mhdawson** [comment]
I think this can be closed as the question was answered and there has been no follow up in a few months. Please let us know if closing was not the right thing to do.
