### ISSUE TITLE
[Question] Is it possible to debug a function returning Napi::Value without JavaScript (node.js) environment?

### ISSUE THREAD

**Issue by RussCoder** [nodejs/node-addon-api#945]
I have a function 

```cpp
Napi::Value myFunction(const Napi::CallbackInfo& info)
```

And I would like to debug it without node.js in Visual Studio.

I added the code: 

```cpp
Napi::Object Init(Napi::Env env, Napi::Object exports) {
    exports.Set("myFunction", Napi::Function::New(env, myFunction));
    return exports;
}

//NODE_API_MODULE(vrem_windows, Init)

void main() {
    Napi::Env env = napi_env();
    auto obj = Init(env, Napi::Object::New(env)); // here is the error
    
    // here I want to invoke the function and print its results to wcout somehow
}
```

I added `napi` headers and `node.lib` to the project, and it compiles well in Visual Studio 2019. 
But it doesn't work. Although `napi_env()` doesn't throw an error, the next line does. The error is about an attempt to access some prohibited memory address. 

I wonder, is it possible to create a dummy `Napi::Env` object and run "Napi" functions in Visual Studio without JavaScript?

**Comment by KevinEady** [comment]
No. In order to do this, you would need to set up a whole Node JS environment into your application, basically embedding Node in your application.

The current paradigm with Node native addons is that the node.exe process starts (which creates the `napi_env`), loads your javascript, and then loads your native addons, passing to it the previously managed `napi_env`s.

FWIW, if you call `napi_env()` like you are doing, you are creating `Napi::Env` that points to an empty napi_env.

**Comment by RussCoder** [comment]
Thank you for the answer.
